"resource/ui/#customizations/hud_customization_frame.res"
{
	"SafeMode"
	{
		"ControlName"				"EditablePanel"
		"fieldName"					"SafeMode"
		"xpos"						"cs-0.5"
		"ypos"						"cs-0.5"
		"wide"						"507"
		"tall"						"320"
		"zpos"						"50"
		"visible"					"1"
		"enabled"					"1"
		"proportionaltoparent"		"1"
		"paintbackground"			"0"
		"border"					"ReplayDefaultBorder"
		
		"Title"
		{
			"ControlName"					"CExLabel"
			"fieldName"						"Title"
			"xpos"							"1"
			"ypos"							"1"
			"zpos"							"-1"
			"wide"							"f2"
			"tall"							"24"
			"visible"						"1"
			"enabled"						"1"
			"proportionaltoparent"			"1"
			"use_proportional_insets"		"1"
			"labelText"						"#TF_OptionCategory_HUD"
			"font"							"HudFontMediumSmallBold"
			"textAlignment"					"center"
			"textinsetx"					"0"
			"fgcolor"						"TanLight"
			"paintBackground"				"1"
			"paintBackgroundtype"			"2"
			"roundedcorners"				"3"
			"bgcolor_override"				"Black"
		}
		
		"CloseButton"
		{
			"ControlName"					"CExButton"
			"fieldName"						"CloseButton"
			"xpos"							"rs1-3"
			"ypos"							"3"
			"zpos"							"20"
			"wide"							"20"
			"tall"							"20"
			"visible"						"1"
			"enabled"						"1"
			"proportionaltoparent"			"1"
			"labelText"						"X"
			"font"							"HudFontMediumSmallBold"
			"textAlignment"					"center"
			"Command"						"engine cl_mainmenu_safemode 0; mat_queue_mode -1; gameui_allowescape"
			"actionsignallevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"
		}

		"WikiButton"
		{
			"ControlName"					"CExButton"
			"fieldName"						"WikiButton"
			"xpos"							"rs1-26"
			"ypos"							"3"
			"zpos"							"20"
			"wide"							"60"
			"tall"							"20"
			"visible"						"1"
			"enabled"						"1"
			"proportionaltoparent"			"1"
			"labelText"						"HUD Wiki"
			"font"							"HudFontSmallestBold"
			"textAlignment"					"center"
			"Command"						"url https://github.com/Eerorri/center-hud/wiki"
			"actionsignallevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"
		}
		
		"Customizations_Scroller"
		{
			"ControlName"					"CScrollableList"
			"fieldName"						"Customizations_Scroller"
			"xpos"							"cs-0.5"
			"ypos"							"26"
			"zpos"							"-1"
			"wide"							"f0"
			"tall"							"239"
			"visible"						"1"
			"enabled"						"1"
			"proportionaltoparent"			"1"
			"paintBackground"				"0"
			"bgcolor_override"				"Gray"
			
			"Scrollbar"
			{

				"xpos"							"rs1+2"
				"ypos"							"0"
				"wide"							"6"
				"tall"							"f0"
				"zpos"							"1000"
				"proportionaltoparent"			"1"
				"nobuttons"						"1"

				"Slider"
				{
					"PaintBackgroundType"		"0"
					"fgcolor_override"			"Gray"
				}
			}
		}

		"ApplyButton"
		{
			"ControlName"					"CExButton"
			"fieldname"						"ApplyButton"
			"xpos"							"7"
			"ypos"							"rs2.5"
			"zpos"							"20"
			"wide"							"162"
			"tall"							"20"
			"visible"						"1"
			"enabled"						"1"
			"proportionaltoparent"			"1"
			"labelText"						"#IT_Apply"
			"font"							"HudFontSmallestBold"
			"textAlignment"					"center"
			"Command"						"engine cl_mainmenu_safemode 0; gameui_allowescape; mat_queue_mode -1; hud_reloadscheme"
			"actionsignallevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"

			"defaultBgColor_override"		"CreditsGreen"
			"armedBgColor_override"			"GreenSolid"
			"depressedBgColor_override"		"GreenSolid"

			"defaultFgColor_override"		"White"
			"armedFgColor_override"			"White"
			"depressedFgColor_override"		"White"
		}

		"ReloadGameButton"
		{
			"ControlName"					"CExButton"
			"fieldName"						"ReloadGameButton"
			"xpos"							"3"
			"ypos"							"0"
			"zpos"							"20"
			"wide"							"162"
			"tall"							"20"
			"visible"						"1"
			"enabled"						"1"
			"proportionaltoparent"			"1"
			"labelText"						"#Vote_RestartGame"
			"font"							"HudFontSmallestBold"
			"textAlignment"					"center"
			"Command"						"engine gameui_allowescape; mat_queue_mode -1; gamemenucommand RestartWithNewLanguage"
			"actionsignallevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"

			"defaultBgColor_override"		"CreditsGreen"
			"armedBgColor_override"			"GreenSolid"
			"depressedBgColor_override"		"GreenSolid"

			"defaultFgColor_override"		"White"
			"armedFgColor_override"			"White"
			"depressedFgColor_override"		"White"

			"pin_to_sibling"				"ApplyButton"
			"pin_corner_to_sibling"			"PIN_TOPLEFT"
			"pin_to_sibling_corner"			"PIN_TOPRIGHT"
		}

		"MinmodeToggle"
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"MinmodeToggle"
			"xpos"					"3"
			"ypos"					"0"
			"zpos"					"16"
			"wide"					"162"
			"tall"					"20"
			"visible"				"1"
			"enabled"				"1"
			"proportionaltoparent"	"1"
			
			"pin_to_sibling"		"ReloadGameButton"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_TOPRIGHT"
			
			"MinmodeButton"
			{
				"controlName"					"CExButton"
				"fieldName"						"MinmodeButton"
				"xpos"							"0"
				"ypos"							"0"
				"wide"							"f0"
				"tall"							"f0"
				"visible"						"1"
				"enabled"						"1"
				"labelText"						""
				"proportionaltoparent"			"1"
				"command"						"engine toggle cl_hud_minmode"
				"actionsignallevel"				"3"
				"sound_depressed"				"UI/buttonclick.wav"
				"sound_released"				"UI/buttonclickrelease.wav"

				"defaultBgColor_override"		"CreditsGreen"
				"armedBgColor_override"			"GreenSolid"
				"depressedBgColor_override"		"GreenSolid"
			}
			
			"MinmodeCheckbox"
			{
				"ControlName"					"CvarToggleCheckButton"
				"fieldName"						"MinmodeCheckbox"
				"xpos"							"0"
				"ypos"							"0"
				"zpos"							"2"
				"wide"							"f0"
				"tall"							"f0"
				"proportionaltoparent"			"1"
				"labeltext"						""
				"smallcheckimage"				"1"
				"button_activation_type"		"1"
				"cvar_name"						"cl_hud_minmode"
				"mouseinputenabled"				"0"

				"defaultFgColor_override"		"White"
				"armedFgColor_override"			"White"
				"depressedFgColor_override"		"White"
			}
			"MinmodeLabel"
			{
				"ControlName"					"CExLabel"
				"fieldName"						"MinmodeLabel"
				"xpos"							"16"
				"ypos"							"0"
				"zpos"							"1"
				"wide"							"f20"
				"tall"							"f0"
				"visible"						"1"
				"enabled"						"1"
				"proportionaltoparent"			"1"
				"labelText"						"#CHud_Menu_MinToggle"
				"font"							"HudFontSmallestBold"
				"textAlignment"					"center"
				"fgcolor"						"White"
				"mouseinputenabled"				"0"
			}
		}

		"ConsoleButton"
		{
			"ControlName"					"CExButton"
			"fieldname"						"ConsoleButton"
			"xpos"							"7"
			"ypos"							"rs1-4"
			"zpos"							"20"
			"wide"							"162"
			"tall"							"20"
			"visible"						"1"
			"enabled"						"1"
			"proportionaltoparent"			"1"
			"labelText"						"#GameUI_Console"
			"font"							"HudFontSmallestBold"
			"textAlignment"					"center"
			"Command"						"engine toggleconsole"
			"actionsignallevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"

			"defaultFgColor_override"		"White"
			"armedFgColor_override"			"White"
			"depressedFgColor_override"		"White"
		}

		"ResetAllButton"
		{
			"ControlName"					"CExButton"
			"fieldName"						"ResetAllButton"
			"xpos"							"3"
			"ypos"							"0"
			"zpos"							"20"
			"wide"							"162"
			"tall"							"20"
			"visible"						"1"
			"enabled"						"1"
			"proportionaltoparent"			"1"
			"labelText"						"#CHud_Menu_ResetOptions"
			"font"							"HudFontSmallestBold"
			"textAlignment"					"center"
			"Command"						"engine customization_reset; hud_crosshair_reset"
			"actionsignallevel"				"2"
			"sound_depressed"				"UI/buttonclick.wav"

			"defaultFgColor_override"		"White"
			"armedFgColor_override"			"White"
			"depressedFgColor_override"		"White"

			"pin_to_sibling"				"ConsoleButton"
			"pin_corner_to_sibling"			"PIN_TOPLEFT"
			"pin_to_sibling_corner"			"PIN_TOPRIGHT"
		}

		"MatchHudToggle"
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"MatchHudToggle"
			"xpos"					"3"
			"ypos"					"0"
			"zpos"					"16"
			"wide"					"162"
			"tall"					"20"
			"visible"				"1"
			"enabled"				"1"
			
			"pin_to_sibling"		"ResetAllButton"
			"pin_corner_to_sibling" "PIN_TOPLEFT"
			"pin_to_sibling_corner" "PIN_TOPRIGHT"
			
			"MatchHudButton"
			{
				"controlName"					"CExButton"
				"fieldName"						"MatchHudButton"
				"xpos"							"0"
				"ypos"							"0"
				"wide"							"f0"
				"tall"							"f0"
				"visible"						"1"
				"enabled"						"1"
				"labelText"						""
				"proportionaltoparent"	"1"
				"command"						"engine toggle tf_use_match_hud"
				"actionsignallevel"				"3"
				"font"							"Default"
				"textAlignment"					"center"
				"sound_depressed"				"UI/buttonclick.wav"
				"sound_released"				"UI/buttonclickrelease.wav"
			}
			
			"MatchHudCheckbox"
			{
				"ControlName"					"CvarToggleCheckButton"
				"fieldName"						"MinmodeCheckbox"
				"xpos"							"0"
				"ypos"							"0"
				"zpos"							"2"
				"wide"							"f0"
				"tall"							"f0"
				"proportionaltoparent"			"1"
				"font"							"Default"
				"labeltext"						""
				"textAlignment"					"center"
				"smallcheckimage"				"1"
				"button_activation_type"		"1"
				"cvar_name"						"tf_use_match_hud"
				"mouseinputenabled"				"0"

				"defaultFgColor_override"		"White"
				"armedFgColor_override"			"White"
				"depressedFgColor_override"		"White"
			}

			"MatchHudLabel"
			{
				"ControlName"					"CExLabel"
				"fieldName"						"MatchHudLabel"
				"xpos"							"16"
				"ypos"							"0"
				"zpos"							"1"
				"wide"							"f20"
				"tall"							"f0"
				"visible"						"1"
				"enabled"						"1"
				"proportionaltoparent"			"1"
				"labelText"						"#CHud_Menu_MatchHudToggle"
				"font"							"HudFontSmallestBold"
				"textAlignment"					"center"
				"fgcolor"						"White"
				"mouseinputenabled"				"0"
			}
		}
	}
}
