"_customizations/hud_customization_quick_settings.res"
{
	"SafeMode"
	{
	"CustomizationPanel"
	{
		
	"CustomizationPanelGeneral"
	{
		"ControlName"			"CScrollableList"
		"fieldName"				"CustomizationPanelGeneral"
		"wide"					"f0"
		"tall"					"f0"
		"visible"				"0"
		"enabled"				"1"
		"proportionaltoparent"	"1"

		"Scrollbar"
		{
			"xpos"					"rs1+1"
			"wide"					"6"
			"tall"					"f0"
			"zpos"					"1000"
			"proportionaltoparent"	"1"

			"Slider"
			{
				"paintBackgroundType"	"0"
				"fgcolor_override"		"TanLight"
			}

			"nobuttons"				"1"
		}

		"TitleBacker"
		{
			"ControlName"				"Panel"
			"fieldName"					"TitleBacker"
			"wide"						"f0"
			"tall"						"35"
			"visible"					"1"
			"paintBackground"			"1"
			"bgcolor_override"			"StoreGreen"
			"proportionaltoparent"		"1"
		}
		"Title"
		{
			"ControlName"				"CExLabel"
			"fieldName"					"Title"
			"xpos"						"-15"
			"ypos"						"2"
			"zpos"						"1"
			"wide"						"0"
			"tall"						"35"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"#CenHud_Custom_Cat_General"
			"font"						"HudFontMediumSmallBold"
			"auto_wide_tocontents"		"1"
			"proportionaltoparent"		"1"

			"pin_to_sibling"		"TitleBacker"
			"pin_to_sibling_corner"	"PIN_CENTER_LEFT"
			"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
		}

		"Info"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"Info"
			"xpos"			"-15"
			"ypos"			"2"
			"zpos"			"2"
			"wide"			"18"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/General"
			"paintBackground"	"0"
			"proportionaltoparent"		"1"

			"pin_to_sibling"	"TitleBacker"
			"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
			"pin_corner_to_sibling"	"PIN_CENTER_RIGHT"

			"image_drawcolor"	"255 255 255 255"
			"image_armedcolor"	"235 235 235 255"
	
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"cs-0.5"
				"ypos"			"cs-0.5"
				"zpos"			"1"
				"wide"			"f0"
				"tall"			"f0"
				"visible"		"1"
				"enabled"		"1"
				"image"			"info"
				"scaleImage"	"1"
				"proportionaltoparent"	"1"
			}
		}

		"Options"
		{
			"ControlName"				"EditablePanel"
			"fieldName"					"Options"
			"xpos"						"cs-0.5"
			"ypos"						"42"	
			"zpos"						"20"
			"wide"						"f15"
			"tall"						"270"
			"visible"					"1"
			"enabled"					"1"
			"proportionaltoparent"		"1"
			
			"TransView"
			{
				"ControlName"						"EditablePanel"
				"fieldName"							"TransView"
				"xpos"								"8"
				"ypos"								"0"
				"wide"								"200"
				"tall"								"84"
				"visible"							"1"
				"enabled"							"1"
				"proportionaltoparent"				"1"

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"zpos"						"5"
					"wide"						"f0"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_TransView"
					"font"						"HudFontSmallBold"
					"wrap"						"1"
					"textAlignment"				"west"
					"use_proportional_insets"	"1"
					"proportionaltoparent"		"1"

					"paintBackground"			"1"
					"bgcolor_override"			"Hitmarker"
					"paintBackgroundType"		"2"
				}
					
				"On"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"On"
					"xpos"								"0"
					"ypos"								"rs1"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Enabled"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"40"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_on"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_clear_viewmodels_on"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
				
				"Off"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Off"
					"xpos"								"4"
					"ypos"								"0"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"

					"pin_to_sibling"					"On"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Disabled"
						"fgcolor"							"TanLight"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"44"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_off"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_clear_viewmodels_off"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
			}			
			"PlayerModel"
			{
				"ControlName"						"EditablePanel"
				"fieldName"							"PlayerModel"
				"xpos"								"5"
				"ypos"								"0"
				"wide"								"200"
				"tall"								"84"
				"visible"							"1"
				"enabled"							"1"
				"proportionaltoparent"				"1"

				"pin_to_sibling"					"TransView"
				"pin_to_sibling_corner"				"PIN_TOPRIGHT"

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"zpos"						"5"
					"wide"						"f0"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_PlayerModel"
					"font"						"HudFontSmallBold"
					"wrap"						"1"
					"textAlignment"				"west"
					"use_proportional_insets"	"1"
					"proportionaltoparent"		"1"
				}
					
				"On"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"On"
					"xpos"								"0"
					"ypos"								"rs1"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Enabled"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"40"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_on"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_on"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
				
				"Off"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Off"
					"xpos"								"4"
					"ypos"								"0"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"

					"pin_to_sibling"					"On"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Disabled"
						"fgcolor"							"TanLight"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"44"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_off"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_off"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
			}
			"SpyDisguise"
			{
				"ControlName"						"EditablePanel"
				"fieldName"							"SpyDisguise"
				"xpos"								"0"
				"ypos"								"5"
				"wide"								"200"
				"tall"								"84"
				"visible"							"1"
				"enabled"							"1"
				"proportionaltoparent"				"1"

				"pin_to_sibling"					"TransView"
				"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"zpos"						"5"
					"wide"						"f0"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_SpyDisguise"
					"font"						"HudFontSmallBold"
					"wrap"						"1"
					"textAlignment"				"west"
					"use_proportional_insets"	"1"
					"proportionaltoparent"		"1"
				}
					
				"On"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"On"
					"xpos"								"0"
					"ypos"								"rs1"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Enabled"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"40"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_on"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_on"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
				
				"Off"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Off"
					"xpos"								"4"
					"ypos"								"0"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"

					"pin_to_sibling"					"On"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Disabled"
						"fgcolor"							"TanLight"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"44"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_off"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_off"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
			}
			"Speedometer"
			{
				"ControlName"						"EditablePanel"
				"fieldName"							"Speedometer"
				"xpos"								"5"
				"ypos"								"0"
				"wide"								"200"
				"tall"								"84"
				"visible"							"1"
				"enabled"							"1"
				"proportionaltoparent"				"1"

				"pin_to_sibling"					"SpyDisguise"
				"pin_to_sibling_corner"				"PIN_TOPRIGHT"

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"zpos"						"5"
					"wide"						"f0"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Speedometer"
					"font"						"HudFontSmallBold"
					"wrap"						"1"
					"textAlignment"				"west"
					"use_proportional_insets"	"1"
					"proportionaltoparent"		"1"
				}
					
				"On"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"On"
					"xpos"								"0"
					"ypos"								"rs1"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Enabled"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"40"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_on"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_on"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
				
				"Off"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Off"
					"xpos"								"4"
					"ypos"								"0"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"

					"pin_to_sibling"					"On"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Disabled"
						"fgcolor"							"TanLight"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"44"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_off"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_off"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
			}
			"UltrawideMode"
			{
				"ControlName"						"EditablePanel"
				"fieldName"							"UltrawideMode"
				"xpos"								"0"
				"ypos"								"5"
				"wide"								"200"
				"tall"								"84"
				"visible"							"1"
				"enabled"							"1"
				"proportionaltoparent"				"1"

				"pin_to_sibling"					"SpyDisguise"
				"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"zpos"						"5"
					"wide"						"f0"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Ultrawide"
					"font"						"HudFontSmallBold"
					"wrap"						"1"
					"textAlignment"				"west"
					"use_proportional_insets"	"1"
					"proportionaltoparent"		"1"
				}
					
				"On"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"On"
					"xpos"								"0"
					"ypos"								"rs1"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Enabled"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"40"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_on"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_on"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
				
				"Off"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Off"
					"xpos"								"4"
					"ypos"								"0"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"

					"pin_to_sibling"					"On"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Disabled"
						"fgcolor"							"TanLight"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"44"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_off"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_off"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
			}
			"SteamDeckMode"
			{
				"ControlName"						"EditablePanel"
				"fieldName"							"SteamDeckMode"
				"xpos"								"5"
				"ypos"								"0"
				"wide"								"200"
				"tall"								"84"
				"visible"							"1"
				"enabled"							"1"
				"proportionaltoparent"				"1"

				"pin_to_sibling"					"UltrawideMode"
				"pin_to_sibling_corner"				"PIN_TOPRIGHT"

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"zpos"						"5"
					"wide"						"f0"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_SteamDeck"
					"font"						"HudFontSmallBold"
					"wrap"						"1"
					"textAlignment"				"west"
					"use_proportional_insets"	"1"
					"proportionaltoparent"		"1"
				}
					
				"On"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"On"
					"xpos"								"0"
					"ypos"								"rs1"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Enabled"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"40"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_on"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_on"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
				
				"Off"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Off"
					"xpos"								"4"
					"ypos"								"0"
					"wide"								"75"
					"tall"								"55"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"

					"pin_to_sibling"					"On"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"Title"
					{
						"ControlName"						"CExLabel"
						"fieldName"							"Title"
						"xpos"								"cs-0.5"
						"ypos"								"0"
						"wide"								"f5"
						"tall"								"12"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"proportionaltoparent"				"1"
						"font"								"ItemFontNameSmall"
						"labeltext"							"#CenHud_Custom_Gen_Disabled"
						"fgcolor"							"TanLight"
					}
					"Image"
					{
						"ControlName"						"ImagePanel"
						"fieldName"							"Image"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"zpos"								"1"
						"wide"								"44"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"mouseinputenabled"					"0"
						"scaleImage"						"1"
						"proportionaltoparent"				"1"
						"image"								"replay/thumbnails/customizations/transparent_viewmodels_off"
					}
					"Button"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Button"
						"xpos"								"cs-0.5"
						"ypos"								"rs1"
						"wide"								"f0"
						"tall"								"f12"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_player_model_off"
						"actionsignallevel"					"5"
						"sound_depressed"					"UI/buttonclick.wav"
					}
				}
			}
		}
	}
	}
	}
}