// TODO: Better looking burger dropdown ico

"_customizations/hud_customization_damage.res"
{
	"SafeMode"
	{
		"CustomizationPanel"
		{
			"CustomizationPanelHealthAmmo"
			{
				"ControlName"			"CScrollableList"
				"fieldName"				"CustomizationPanelHealthAmmo"
				"wide"					"f0"
				"tall"					"f0"
				"visible"				"0"
				"enabled"				"1"
				"proportionaltoparent"	"1"

				"Scrollbar"
				{
					"xpos"					"rs1+1"
					"wide"					"6"
					"tall"					"f0"
					"zpos"					"1000"
					"proportionaltoparent"	"1"

					"Slider"
					{
						"paintBackgroundType"	"0"
						"fgcolor_override"		"Gray"
					}

					"nobuttons"				"1"
				}

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"cs-0.5"
					"ypos"						"8"
					"wide"						"f30"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Cat_HealthAndAmmo"
					"font"						"HudFontMediumBold"
					"textAlignment"				"west"
					"fgcolor"					"White"
					"proportionaltoparent"		"1"
				}				
				
				"Info"
				{
					"ControlName"	"CExImageButton"
					"fieldName"		"Info"
					"xpos"			"rs1-20"
					"ypos"			"15"
					"zpos"			"7"
					"wide"			"15"
					"tall"			"15"
					"visible"		"1"
					"enabled"		"1"
					"labelText"		""
					"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Health"
					"paintBackground"	"0"
					"proportionaltoparent"		"1"
					"sound_depressed"	"UI/buttonclick.wav"
					"sound_released"	"UI/buttonclickrelease.wav"

					"image_drawcolor"	"255 255 255 255"
					"image_armedcolor"	"200 200 200 255"
			
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"zpos"			"1"
						"wide"			"f0"
						"tall"			"f0"
						"visible"		"1"
						"enabled"		"1"
						"image"			"info"
						"scaleImage"	"1"
						"proportionaltoparent"	"1"
					}
				}

				"Options"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"Options"
					"xpos"						"cs-0.5"
					"ypos"						"40"	
					"zpos"						"20"
					"wide"						"f20"
					"tall"						"285"
					"visible"					"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"

					"Health"
					{
						"ControlName"				"CMatchHistoryEntryPanel"
						"fieldName"					"Health"
						"xpos"						"0"
						"ypos"						"0"
						"zpos"						"50"
						"wide"						"f0"
						"tall"						"165"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"

						"ignorescheme"				"1"

						"collapsed_height"			"165"
						"expanded_height"			"29"
						"resize_time"				"0.4"

						"Container"			{ "visible" "0" }
						"BottomStats"		{ "visible" "0" }

						"Title"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Title"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"10"
							"wide"						"0"
							"tall"						"25"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					"#CenHud_Custom_Cat_Health"
							"font"						"HudFontSmallBold"
							"textinsetx"				"10"
							"textinsety"				"0.5"
							"fgcolor"					"White"
							"auto_wide_tocontents"		"1"
							"use_proportional_insets"	"1"
							"proportionaltoparent"		"1"

							"pin_to_sibling"	"TitleBG"
						}

						"TitleBG"
						{
							"ControlName"				"Panel"
							"fieldName"					"TitleBG"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f10"
							"tall"						"25"
							"visible"					"1"
							"enabled"					"1"
							"bgcolor_override"			"StoreGreen"
							"paintBackgroundType"		"2"
							"proportionaltoparent"		"1"
							"roundedcorners"			"3"
							"proportionaltoparent"		"1"
						}

						"Info"
						{
							"ControlName"	"CExImageButton"
							"fieldName"		"Info"
							"xpos"			"5"
							"ypos"			"0"
							"zpos"			"15"
							"wide"			"15"
							"tall"			"15"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		""
							"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Customizations#HealthValue"
							"paintBackground"	"0"
							"sound_depressed"	"UI/buttonclick.wav"
							"sound_released"	"UI/buttonclickrelease.wav"

							"pin_to_sibling"	"Title"
							"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
							"pin_corner_to_sibling"	"PIN_CENTER_LEFT"

							"image_drawcolor"	"255 255 255 255"
							"image_armedcolor"	"200 200 200 255"
					
							"SubImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"SubImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"enabled"		"1"
								"image"			"info"
								"scaleImage"	"1"
								"proportionaltoparent"	"1"
							}
						}

						"OpenClosePanel"
						{
							"ControlName"	"CExImageButton"
							"fieldName"		"OpenClosePanel"
							"xpos"			"-5"
							"ypos"			"0"
							"zpos"			"15"
							"wide"			"18"
							"tall"			"18"
							"command"		"toggle_collapse"
							"paintBackground"	"0"
							"labeltext"			""
							"sound_depressed"	"UI/buttonclick.wav"
							"sound_released"	"UI/buttonclickrelease.wav"
							
							"use_proportional_insets"	"1"
							"proportionaltoparent"		"1"

							"image_drawcolor"	"255 255 255 255"
							"image_armedcolor"	"200 200 200 255"

							"pin_to_sibling"	"TitleBG"
							"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
							"pin_corner_to_sibling"	"PIN_CENTER_RIGHT"

							"SubImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"SubImage"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"enabled"		"1"
								"scaleImage"	"1"
								"image"			"replay/thumbnails/menu/glyph/burgermenu"
								"proportionaltoparent"	"1"
							}	
						}

						"Separator"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"Separator"
							"xpos"						"0"
							"ypos"						"2"
							"wide"						"f10"
							"tall"						"2"
							"visible"					"1"
							"enabled"					"1"
							"paintBackgroundtype"		"0"
							"bgcolor_override"			"TanDark"
							"proportionaltoparent"		"1"

							"pin_to_sibling"			"TitleBG"
							"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
							"pin_corner_to_sibling"		"PIN_CENTER_TOP"
						}

						"On"
						{
							"ControlName"					"CExButton"
							"fieldName"						"On"
							"xpos"							"-5"
							"ypos"							"8"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"25"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_Enabled"
							"textAlignment"					"center"
							"font"							"HudFontSmallBold"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"5"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"pin_to_sibling"				"Separator"
							"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
						}
						"Off"
						{
							"ControlName"					"CExButton"
							"fieldName"						"Off"
							"xpos"							"5"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"25"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_Disabled"
							"textAlignment"					"center"
							"font"							"HudFontSmallBold"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"5"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"pin_to_sibling"				"On"
							"pin_to_sibling_corner"			"PIN_TOPRIGHT"
						}
								
						"FontSubTitle"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"FontSubTitle"
							"xpos"						"0"
							"ypos"						"4"
							"wide"						"f0"
							"tall"						"15"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					"#CenHud_Custom_Gen_Font"
							"font"						"HudFontSmallestBold"
							"textAlignment"				"west"
							"fgcolor"					"Gray"
							"proportionaltoparent"		"1"

							"pin_to_sibling"			"On"
							"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
						}
						"FontOption"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"FontOption"
							"xpos"						"0"
							"ypos"						"3"
							"wide"						"f0"
							"tall"						"30"
							"visible"					"1"
							"enabled"					"1"
							"proportionaltoparent"		"1"
							"pin_to_sibling"			"FontSubTitle"
							"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

							"Font"
							{
								"ControlName"					"CExButton"
								"fieldName"						"Font"
								"xpos"							"0"
								"ypos"							"0"
								"zpos"							"5"
								"wide"							"0"
								"tall"							"30"
								"visible"						"1"
								"enabled"						"1"
								"labelText"						"Secondary"
								"textAlignment"					"center"
								"font"							"HudFontSmallOutline"
								"textinsetx"					"25"
								"textinsety"					"2"
								"command"						""
								"actionsignallevel"				"7"
								"auto_wide_tocontents"			"1"
								"proportionaltoparent"			"1"
								"use_proportional_insets"		"1"
								"sound_depressed"		"UI/buttonclick.wav"
								"sound_released"		"UI/buttonclickrelease.wav"

							}

							"FontBold"
							{
								"ControlName"					"CExButton"
								"fieldName"						"FontBold"
								"xpos"							"5"
								"ypos"							"0"
								"zpos"							"5"
								"wide"							"0"
								"tall"							"30"
								"visible"						"1"
								"enabled"						"1"
								"labelText"						"Bold"
								"textAlignment"					"center"
								"font"							"HudFontSmallBoldOutline"
								"textinsetx"					"25"
								"command"						""
								"actionsignallevel"				"7"
								"auto_wide_tocontents"			"1"
								"proportionaltoparent"			"1"
								"use_proportional_insets"		"1"
								"sound_depressed"		"UI/buttonclick.wav"
								"sound_released"		"UI/buttonclickrelease.wav"

								"pin_to_sibling"	"Font"
								"pin_to_sibling_corner"	"PIN_TOPRIGHT"
							}

							"FontNoutline"
							{
								"ControlName"					"CExButton"
								"fieldName"						"FontNoutline"
								"xpos"							"5"
								"ypos"							"0"
								"zpos"							"5"
								"wide"							"0"
								"tall"							"30"
								"visible"						"1"
								"enabled"						"1"
								"labelText"						"Secondary"
								"textAlignment"					"center"
								"font"							"HudFontSmall"
								"textinsetx"					"25"
								"textinsety"					"2"
								"command"						""
								"actionsignallevel"				"7"
								"auto_wide_tocontents"			"1"
								"proportionaltoparent"			"1"
								"use_proportional_insets"		"1"
								"sound_depressed"		"UI/buttonclick.wav"
								"sound_released"		"UI/buttonclickrelease.wav"

								"pin_to_sibling"	"FontBold"
								"pin_to_sibling_corner"	"PIN_TOPRIGHT"
							}
							"FontNoutlineBold"
							{
								"ControlName"					"CExButton"
								"fieldName"						"FontNoutlineBold"
								"xpos"							"5"
								"ypos"							"0"
								"zpos"							"5"
								"wide"							"0"
								"tall"							"30"
								"visible"						"1"
								"enabled"						"1"
								"labelText"						"Bold"
								"textAlignment"					"center"
								"font"							"HudFontSmallBold"
								"textinsetx"					"25"
								"command"						""
								"actionsignallevel"				"7"
								"auto_wide_tocontents"			"1"
								"proportionaltoparent"			"1"
								"use_proportional_insets"		"1"
								"sound_depressed"		"UI/buttonclick.wav"
								"sound_released"		"UI/buttonclickrelease.wav"

								"pin_to_sibling"	"FontNoutline"
								"pin_to_sibling_corner"	"PIN_TOPRIGHT"
							}
						}

						"HealFontSubTitle"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"HealFontSubTitle"
							"xpos"						"0"
							"ypos"						"4"
							"wide"						"f0"
							"tall"						"15"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					"#CenHud_Custom_Health_HealValue"
							"font"						"HudFontSmallestBold"
							"textAlignment"				"west"
							"fgcolor"					"Gray"
							"proportionaltoparent"		"1"

							"pin_to_sibling"			"FontOption"
							"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
						}
						"HealFontOption"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"HealFontOption"
							"xpos"						"0"
							"ypos"						"3"
							"wide"						"f0"
							"tall"						"30"
							"visible"					"1"
							"enabled"					"1"
							"proportionaltoparent"		"1"
							"pin_to_sibling"			"HealFontSubTitle"
							"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

							"Font"
							{
								"ControlName"					"CExButton"
								"fieldName"						"Font"
								"xpos"							"0"
								"ypos"							"0"
								"zpos"							"5"
								"wide"							"0"
								"tall"							"30"
								"visible"						"1"
								"enabled"						"1"
								"labelText"						"Secondary"
								"textAlignment"					"center"
								"font"							"HudFontSmallOutline"
								"textinsetx"					"25"
								"textinsety"					"2"
								"command"						""
								"actionsignallevel"				"7"
								"auto_wide_tocontents"			"1"
								"proportionaltoparent"			"1"
								"use_proportional_insets"		"1"
								"sound_depressed"		"UI/buttonclick.wav"
								"sound_released"		"UI/buttonclickrelease.wav"

							}

							"FontBold"
							{
								"ControlName"					"CExButton"
								"fieldName"						"FontBold"
								"xpos"							"5"
								"ypos"							"0"
								"zpos"							"5"
								"wide"							"0"
								"tall"							"30"
								"visible"						"1"
								"enabled"						"1"
								"labelText"						"Bold"
								"textAlignment"					"center"
								"font"							"HudFontSmallBoldOutline"
								"textinsetx"					"25"
								"command"						""
								"actionsignallevel"				"7"
								"auto_wide_tocontents"			"1"
								"proportionaltoparent"			"1"
								"use_proportional_insets"		"1"
								"sound_depressed"		"UI/buttonclick.wav"
								"sound_released"		"UI/buttonclickrelease.wav"

								"pin_to_sibling"	"Font"
								"pin_to_sibling_corner"	"PIN_TOPRIGHT"
							}

							"FontNoutline"
							{
								"ControlName"					"CExButton"
								"fieldName"						"FontNoutline"
								"xpos"							"5"
								"ypos"							"0"
								"zpos"							"5"
								"wide"							"0"
								"tall"							"30"
								"visible"						"1"
								"enabled"						"1"
								"labelText"						"Secondary"
								"textAlignment"					"center"
								"font"							"HudFontSmall"
								"textinsetx"					"25"
								"textinsety"					"2"
								"command"						""
								"actionsignallevel"				"7"
								"auto_wide_tocontents"			"1"
								"proportionaltoparent"			"1"
								"use_proportional_insets"		"1"
								"sound_depressed"		"UI/buttonclick.wav"
								"sound_released"		"UI/buttonclickrelease.wav"

								"pin_to_sibling"	"FontBold"
								"pin_to_sibling_corner"	"PIN_TOPRIGHT"
							}
							"FontNoutlineBold"
							{
								"ControlName"					"CExButton"
								"fieldName"						"FontNoutlineBold"
								"xpos"							"5"
								"ypos"							"0"
								"zpos"							"5"
								"wide"							"0"
								"tall"							"30"
								"visible"						"1"
								"enabled"						"1"
								"labelText"						"Bold"
								"textAlignment"					"center"
								"font"							"HudFontSmallBold"
								"textinsetx"					"25"
								"command"						""
								"actionsignallevel"				"7"
								"auto_wide_tocontents"			"1"
								"proportionaltoparent"			"1"
								"use_proportional_insets"		"1"
								"sound_depressed"		"UI/buttonclick.wav"
								"sound_released"		"UI/buttonclickrelease.wav"

								"pin_to_sibling"	"FontNoutline"
								"pin_to_sibling_corner"	"PIN_TOPRIGHT"
							}
						}
					}
				}
			}
		}
	}
}