"_customizations/hud_customization_folder.res"
{
	"SafeMode"
	{
		"FolderNameWarning"
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"FolderNameWarning"
			"zpos"					"1000"
			"wide"					"f0"
			"tall"					"f0"
			"visible"				"1"
			"enabled"				"1"
			"border"				"GrayDialogBorder"
			"proportionaltoparent"	"1"

			"CloseButton"
			{
				"ControlName"				"CExButton"
				"fieldName"					"CloseButton"
				"xpos"						"rs1-7"
				"ypos"						"7"
				"wide"						"22"
				"tall"						"22"
				"visible"					"1"
				"enabled"					"1"
				"labelText"					"X"
				"font"						"HudFontMediumSmallBold"
				"textAlignment"				"center"
				"command"					"engine cl_mainmenu_safemode 0; mat_queue_mode -1; gameui_allowescape"
				"actionsignallevel"			"3"
				"proportionaltoparent"		"1"
				"use_proportional_insets"	"1"
				"sound_depressed"		"UI/buttonclick.wav"
				"sound_released"		"UI/buttonclickrelease.wav"
			}

			"WikiButton"
			{
				"ControlName"				"CExButton"
				"fieldName"					"WikiButton"
				"xpos"						"5"
				"wide"						"0"
				"tall"						"22"
				"visible"					"1"
				"enabled"					"1"
				"labelText"					"#CenHud_Menu_HUDWiki"
				"font"						"HudFontSmallestBold"
				"textAlignment"				"center"
				"textinsetx"				"30"
				"command"					"url https://github.com/RoseyLemonz/center-hud/wiki"
				"proportionaltoparent"		"1"
				"auto_wide_tocontents"		"1"
				"sound_depressed"		"UI/buttonclick.wav"
				"sound_released"		"UI/buttonclickrelease.wav"

				"defaultBgColor_override"	"80 90 190 255"
				"armedBgColor_override"		"60 70 170 255"
				"depressedBgColor_override"	"60 70 170 255"

				"defaultFgColor_override"	"White"
				"armedFgColor_override"		"White"
				"depressedFgColor_override"	"White"

				"pin_to_sibling"			"CloseButton"
				"pin_corner_to_sibling"		"PIN_TOPRIGHT"
				"pin_to_sibling_corner"		"PIN_TOPLEFT"
			}

			"TroubleshootingButton"
			{
				"ControlName"				"CExButton"
				"fieldName"					"TroubleshootingButton"
				"xpos"						"5"
				"tall"						"22"
				"wide"						"0"
				"visible"					"1"
				"enabled"					"1"
				"labelText"					"#CenHud_Menu_Troubleshooting"
				"font"						"HudFontSmallestBold"
				"textAlignment"				"center"
				"textinsetx"				"30"
				"command"					"url https://github.com/RoseyLemonz/center-hud/wiki/Troubleshooting"
				"actionsignallevel"			"3"
				"proportionaltoparent"		"1"
				"auto_wide_tocontents"		"1"
				"sound_depressed"		"UI/buttonclick.wav"
				"sound_released"		"UI/buttonclickrelease.wav"

				"defaultBgColor_override"	"200 140 50 255"
				"armedBgColor_override"		"170 110 30 255"
				"depressedBgColor_override"	"170 110 30 255"

				"defaultFgColor_override"	"White"
				"armedFgColor_override"		"White"
				"depressedFgColor_override"	"White"

				"pin_to_sibling"			"WikiButton"
				"pin_corner_to_sibling"		"PIN_TOPRIGHT"
				"pin_to_sibling_corner"		"PIN_TOPLEFT"
			}

			"WarningTitle"
			{
				"ControlName"				"CExLabel"
				"fieldName"					"WarningTitle"
				"xpos"						"cs-0.5"
				"ypos"						"70"
				"wide"						"f20"
				"tall"						"50"
				"visible"					"1"
				"enabled"					"1"
				"labelText"					"#CenHud_Foldercheck_Warning"
				"font"						"HudFontGiantBold"
				"textAlignment"				"center"
				"fgcolor"					"TeamRed"
				"proportionaltoparent"		"1"
			}
			"DescriptionPart1"
			{
				"ControlName"				"CExLabel"
				"fieldName"					"DescriptionPart1"
				"wide"						"f100"
				"tall"						"0"
				"visible"					"1"
				"enabled"					"1"
				"labelText"					"#CenHud_Foldercheck_Part1"
				"font"						"HudFontSmall"
				"textAlignment"				"center"
				"fgcolor"					"Gray"
				"centerwrap"				"1"
				"auto_tall_tocontents"		"1"
				"proportionaltoparent"		"1"

				"pin_to_sibling"			"WarningTitle"
				"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
				"pin_corner_to_sibling"		"PIN_CENTER_TOP"
			}
			"HudFolder"
			{
				"ControlName"				"CExLabel"
				"fieldName"					"HudFolder"
				"ypos"						"5"
				"zpos"						"0"
				"wide"						"f100"
				"tall"						"25"
				"visible"					"1"
				"enabled"					"1"
				"labelText"					"center-hud"
				"font"						"HudFontGiantSecondary"
				"textAlignment"				"center"
				"fgcolor"					"White"
				"proportionaltoparent"		"1"

				"pin_to_sibling"			"DescriptionPart1"
				"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
				"pin_corner_to_sibling"		"PIN_CENTER_TOP"
			}
			"DescriptionPart2"
			{
				"ControlName"				"CExLabel"
				"fieldName"					"DescriptionPart2"
				"xpos"						"0"
				"ypos"						"10"
				"zpos"						"0"
				"wide"						"f100"
				"tall"						"0"
				"visible"					"1"
				"enabled"					"1"
				"labelText"					"#CenHud_Foldercheck_Part2"
				"font"						"HudFontSmall"
				"textAlignment"				"center"
				"fgcolor"					"Gray"
				"centerwrap"				"1"
				"auto_tall_tocontents"		"1"
				"proportionaltoparent"		"1"

				"pin_to_sibling"			"HudFolder"
				"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
				"pin_corner_to_sibling"		"PIN_CENTER_TOP"
			}
		}
	}
}