"_customizations/hud_customization_quick_settings.res"
{
	"SafeMode"
	{
		"CustomizationPanel"
		{
			"CustomizationPanelQuick"
			{
				"ControlName"			"CScrollableList"
				"fieldName"				"CustomizationPanelQuick"
				"wide"					"f0"
				"tall"					"f0"
				"visible"				"0"
				"enabled"				"1"
				"proportionaltoparent"	"1"

				"Scrollbar"
				{
					"xpos"					"rs1+1"
					"wide"					"6"
					"tall"					"f0"
					"zpos"					"1000"
					"proportionaltoparent"	"1"

					"Slider"
					{
						"paintBackgroundType"	"0"
						"fgcolor_override"		"Gray"
					}

					"nobuttons"				"1"
				}

				"QuickTitle"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"QuickTitle"
					"xpos"						"cs-0.5"
					"ypos"						"8"
					"wide"						"f30"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Cat_Quick"
					"font"						"HudFontMediumBold"
					"textAlignment"				"west"
					"fgcolor"					"White"
					"proportionaltoparent"		"1"
				}

				"QuickInfo"
				{
					"ControlName"	"CExImageButton"
					"fieldName"		"QuickInfo"
					"xpos"			"rs1-20"
					"ypos"			"15"
					"zpos"			"7"
					"wide"			"15"
					"tall"			"15"
					"visible"		"1"
					"enabled"		"1"
					"labelText"		""
					"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Quick-Settings"
					"paintBackground"	"0"
					"proportionaltoparent"		"1"

					"image_drawcolor"	"255 255 255 255"
					"image_armedcolor"	"200 200 200 255"
			
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"zpos"			"1"
						"wide"			"f0"
						"tall"			"f0"
						"visible"		"1"
						"enabled"		"1"
						"image"			"info"
						"scaleImage"	"1"
						"proportionaltoparent"	"1"
					}
				}

				"Options"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"Options"
					"xpos"						"cs-0.5"
					"ypos"						"40"	
					"zpos"						"20"
					"wide"						"f20"
					"tall"						"210"
					"visible"					"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					
					"ChatToggle"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"ChatToggle"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"120"
						"tall"						"22"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle hud_saytext_time 0 12"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"zpos"						"1"
							"wide"						"o1"
							"tall"						"f0"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"hud_saytext_time"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"24"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_Quick_ShowChat"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"NetgraphToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"NetgraphToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"ChatToggle"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle net_graph 0 1"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"zpos"						"1"
							"wide"						"o1"
							"tall"						"f0"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"net_graph"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"24"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_Quick_ShowNet"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"ShowposToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"ShowposToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"NetgraphToggle"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_showpos 0 1"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"zpos"						"1"
							"wide"						"o1"
							"tall"						"f0"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_showpos"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"24"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_Quick_ShowPos"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"ShowFPSToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"ShowFPSToggle"
						"xpos"							"0"
						"ypos"							"3"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"ChatToggle"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_showfps 0 1"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"zpos"						"1"
							"wide"						"o1"
							"tall"						"f0"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_showfps"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"24"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_Quick_ShowFPS"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"ContractsToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"ContractsToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"135"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"ShowFPSToggle"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle tf_contract_progress_show 0 1"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"zpos"						"1"
							"wide"						"o1"
							"tall"						"f0"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"tf_contract_progress_show"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"24"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_Quick_ShowCon"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"MinmodeToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"MinmodeToggle"
						"xpos"							"0"
						"ypos"							"3"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"ShowFPSToggle"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_hud_minmode 0 1"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"zpos"						"1"
							"wide"						"o1"
							"tall"						"f0"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_hud_minmode"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"24"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_Quick_UseMin"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"MatchStatusToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"MatchStatusToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"MinmodeToggle"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle tf_use_match_hud 0 1"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"zpos"						"1"
							"wide"						"o1"
							"tall"						"f0"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"tf_use_match_hud"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"24"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_Quick_ShowMS"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"CharModelToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"CharModelToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"MatchStatusToggle"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_hud_playerclass_use_playermodel 0 1"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"zpos"						"1"
							"wide"						"o1"
							"tall"						"f0"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_hud_playerclass_use_playermodel"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"24"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_Quick_Use3D"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"StreamerMode"
					{
						"ControlName"				"CMatchHistoryEntryPanel"
						"fieldName"					"StreamerMode"
						"xpos"						"0"
						"ypos"						"80"
						"zpos"						"50"
						"wide"						"f0"
						"tall"						"125"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"

						"ignorescheme"				"1"

						"collapsed_height"			"125"
						"expanded_height"			"29"
						"resize_time"				"0.4"

						"Container"			{ "visible" "0" }
						"BottomStats"		{ "visible" "0" }

						"Title"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Title"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"10"
							"wide"						"0"
							"tall"						"25"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					"#CenHud_Custom_Quick_Stream_Title"
							"font"						"HudFontSmallBold"
							"textinsetx"				"10"
							"textinsety"				"0.5"
							"fgcolor"					"White"
							"auto_wide_tocontents"		"1"
							"use_proportional_insets"	"1"
							"proportionaltoparent"		"1"

							"pin_to_sibling"	"TitleBG"
						}

						"TitleBG"
						{
							"ControlName"				"Panel"
							"fieldName"					"TitleBG"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f10"
							"tall"						"25"
							"visible"					"1"
							"enabled"					"1"
							"bgcolor_override"			"StoreGreen"
							"paintBackgroundType"		"2"
							"proportionaltoparent"		"1"
							"roundedcorners"			"3"
							"proportionaltoparent"		"1"
						}

						"Info"
						{
							"ControlName"	"CExImageButton"
							"fieldName"		"Info"
							"xpos"			"5"
							"ypos"			"0"
							"zpos"			"15"
							"wide"			"15"
							"tall"			"15"
							"visible"		"1"
							"enabled"		"1"
							"labelText"		""
							"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Customizations#Streamer-Mode"
							"paintBackground"	"0"
							"sound_depressed"	"UI/buttonclick.wav"
							"sound_released"	"UI/buttonclickrelease.wav"

							"pin_to_sibling"	"Title"
							"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
							"pin_corner_to_sibling"	"PIN_CENTER_LEFT"

							"image_drawcolor"	"255 255 255 255"
							"image_armedcolor"	"200 200 200 255"
					
							"SubImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"SubImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"enabled"		"1"
								"image"			"info"
								"scaleImage"	"1"
								"proportionaltoparent"	"1"
							}
						}

						"OpenClosePanel"
						{
							"ControlName"	"CExImageButton"
							"fieldName"		"OpenClosePanel"
							"xpos"			"-5"
							"ypos"			"0"
							"zpos"			"15"
							"wide"			"18"
							"tall"			"18"
							"command"		"toggle_collapse"
							"paintBackground"	"0"
							"labeltext"			""
							"sound_depressed"	"UI/buttonclick.wav"
							"sound_released"	"UI/buttonclickrelease.wav"
							
							"use_proportional_insets"	"1"
							"proportionaltoparent"		"1"

							"image_drawcolor"	"255 255 255 255"
							"image_armedcolor"	"200 200 200 255"

							"pin_to_sibling"	"TitleBG"
							"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
							"pin_corner_to_sibling"	"PIN_CENTER_RIGHT"

							"SubImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"SubImage"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"enabled"		"1"
								"scaleImage"	"1"
								"image"			"replay/thumbnails/menu/glyph/burgermenu"
								"proportionaltoparent"	"1"
							}	
						}

						"Separator"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"Separator"
							"xpos"						"0"
							"ypos"						"2"
							"wide"						"f10"
							"tall"						"2"
							"visible"					"1"
							"enabled"					"1"
							"paintBackgroundtype"		"0"
							"bgcolor_override"			"TanDark"
							"proportionaltoparent"		"1"

							"pin_to_sibling"			"TitleBG"
							"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
							"pin_corner_to_sibling"		"PIN_CENTER_TOP"
						}
						"Message"
						{
							"ControlName"					"CExLabel"
							"fieldName"						"Message"
							"xpos"							"-5"
							"ypos"							"5"
							"zpos"							"1"
							"wide"							"f10"
							"tall"							"0"
							"visible"						"1"
							"enabled"						"1"
							"wrap"							"1"
							"font"							"HudFontSmallest"
							"labeltext"						"#CenHud_Custom_Quick_Stream_Message"
							"textAlignment"					"north-west"
							"fgcolor"						"Gray"
							"auto_tall_tocontents"			"1"
							"mouseinputenabled"				"0"
							"proportionaltoparent"			"1"

							"pin_to_sibling"				"Separator"
							"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
						}

						// TODO: Implement

						"On"
						{
							"ControlName"					"CExButton"
							"fieldName"						"On"
							"xpos"							"0"
							"ypos"							"6"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"25"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_Enabled"
							"textAlignment"					"center"
							"font"							"HudFontSmallBold"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"7"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"pin_to_sibling"				"Message"
							"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
						}
						"Off"
						{
							"ControlName"					"CExButton"
							"fieldName"						"Off"
							"xpos"							"5"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"25"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_Disabled"
							"textAlignment"					"center"
							"font"							"HudFontSmallBold"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"7"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"pin_to_sibling"				"On"
							"pin_to_sibling_corner"			"PIN_TOPRIGHT"
						}
						"Warning"
						{
							"ControlName"					"CExLabel"
							"fieldName"						"Warning"
							"ypos"							"6"
							"zpos"							"1"
							"tall"							"0"
							"wide"							"f10"
							"visible"						"1"
							"enabled"						"1"
							"labeltext"						"#CenHud_Custom_Quick_Stream_Warning"
							"font"							"HudFontSmallest"
							"textAlignment"					"north-west"
							"fgcolor"						"TeamRed"
							"wrap"							"1"
							"auto_tall_tocontents"			"1"
							"mouseinputenabled"				"0"
							"proportionaltoparent"			"1"

							"pin_to_sibling"				"On"
							"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
						}
					}
				}
			}
		}
	}
}