"_customizations/hud_customization_damage.res"
{
	"SafeMode"
	{
	"CustomizationPanel"
	{

	"CustomizationPanelCrosshairs"
	{
		"ControlName"			"EditablePanel"
		"fieldName"				"CustomizationPanelCrosshairs"
		"wide"					"f0"
		"tall"					"f0"
		"visible"				"0"
		"enabled"				"1"
		"proportionaltoparent"	"1"

		"TitleBacker"
		{
			"ControlName"				"Panel"
			"fieldName"					"TitleBacker"
			"wide"						"f0"
			"tall"						"35"
			"visible"					"1"
			"paintBackground"			"1"
			"bgcolor_override"			"QuestGold"
			"proportionaltoparent"		"1"
		}
		"Title"
		{
			"ControlName"				"CExLabel"
			"fieldName"					"Title"
			"xpos"						"-15"
			"ypos"						"2"
			"zpos"						"1"
			"wide"						"0"
			"tall"						"35"
			"visible"					"1"
			"enabled"					"1"
			"labelText"					"#CenHud_Custom_Cat_Crosshairs"
			"font"						"HudFontMediumSmallBold"
			"fgcolor_override"			"White"
			"auto_wide_tocontents"		"1"
			"proportionaltoparent"		"1"

			"pin_to_sibling"		"TitleBacker"
			"pin_to_sibling_corner"	"PIN_CENTER_LEFT"
			"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
		}

		"Info"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"Info"
			"xpos"			"-15"
			"ypos"			"2"
			"zpos"			"2"
			"wide"			"18"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Crosshairs"
			"paintBackground"	"0"
			"proportionaltoparent"		"1"

			"pin_to_sibling"	"TitleBacker"
			"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
			"pin_corner_to_sibling"	"PIN_CENTER_RIGHT"

			"image_drawcolor"	"255 255 255 255"
			"image_armedcolor"	"235 235 235 255"
	
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"cs-0.5"
				"ypos"			"cs-0.5"
				"zpos"			"1"
				"wide"			"f0"
				"tall"			"f0"
				"visible"		"1"
				"enabled"		"1"
				"image"			"info"
				"scaleImage"	"1"
				"proportionaltoparent"	"1"
			}
		}

		"Options"
		{
			"ControlName"				"EditablePanel"
			"fieldName"					"Options"
			"xpos"						"cs-0.5"
			"ypos"						"42"	
			"zpos"						"20"
			"wide"						"f15"
			"tall"						"185"
			"visible"					"1"
			"enabled"					"1"
			"proportionaltoparent"		"1"

			"On"
			{
				"ControlName"					"CExButton"
				"fieldName"						"On"
				"xpos"							"5"
				"ypos"							"4"
				"zpos"							"5"
				"wide"							"0"
				"tall"							"25"
				"visible"						"1"
				"enabled"						"1"
				"allcaps"						"1"
				"labelText"						"#CenHud_Custom_Gen_On"
				"textAlignment"					"center"
				"font"							"HudFontSmallBold"
				"textinsetx"					"25"
				"command"						"engine hud_xhair_on; cl_crosshair_scale 0"
				"actionsignallevel"				"5"
				"auto_wide_tocontents"			"1"
				"proportionaltoparent"			"1"
				"use_proportional_insets"		"1"
				"sound_depressed"		"UI/buttonclick.wav"
				"sound_released"		"UI/buttonclickrelease.wav"
			}
			"Off"
			{
				"ControlName"					"CExButton"
				"fieldName"						"Off"
				"xpos"							"5"
				"ypos"							"0"
				"zpos"							"5"
				"wide"							"0"
				"tall"							"25"
				"visible"						"1"
				"enabled"						"1"
				"allcaps"						"1"
				"labelText"						"#CenHud_Custom_Gen_Off"
				"textAlignment"					"center"
				"font"							"HudFontSmallBold"
				"textinsetx"					"25"
				"command"						"engine hud_xhair_off; cl_crosshair_scale 32"
				"actionsignallevel"				"5"
				"auto_wide_tocontents"			"1"
				"proportionaltoparent"			"1"
				"use_proportional_insets"		"1"
				"sound_depressed"		"UI/buttonclick.wav"
				"sound_released"		"UI/buttonclickrelease.wav"

				"pin_to_sibling"				"On"
				"pin_to_sibling_corner"			"PIN_TOPRIGHT"
			}

			"Size"
			{
				"ControlName"				"EditablePanel"
				"fieldName"					"Size"
				"xpos"						"10"
				"ypos"						"4"
				"zpos"						"50"
				"wide"						"280"
				"tall"						"55"
				"visible"					"1"
				"enabled"					"1"
				"proportionaltoparent"		"1"

				"pin_to_sibling"	"Off"
				"pin_to_sibling_corner"	"PIN_TOPRIGHT"

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"zpos"						"10"
					"tall"						"15"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Gen_Size"
					"font"						"HudFontSmallBold"
					"auto_wide_tocontents"		"1"
					"use_proportional_insets"	"1"
					"proportionaltoparent"		"1"
				}

				"Options"
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"Options"
					"xpos"							"0"
					"ypos"							"15"
					"zpos"							"20"
					"wide"							"f0"
					"tall"							"15"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintbackground"				"0"
					"paintBackgroundType"			"0"

					"Size_12"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Size_12"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"use_proportional_insets"			"1"
						"labelText"							"12"
						"auto_wide_tocontents"				"1"
						"auto_tall_tocontents"				"1"
						"font"								"HudFontSmallBold"
						"textinsetx"						"10"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_size_12"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"
					}
					"Size_14"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Size_14"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"use_proportional_insets"			"1"
						"labelText"							"14"
						"auto_wide_tocontents"				"1"
						"auto_tall_tocontents"				"1"
						"font"								"HudFontSmallBold"
						"textinsetx"						"10"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_size_14"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"
	
						"pin_to_sibling"					"Size_12"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Size_16"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Size_16"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"use_proportional_insets"			"1"
						"labelText"							"16"
						"auto_wide_tocontents"				"1"
						"auto_tall_tocontents"				"1"
						"font"								"HudFontSmallBold"
						"textinsetx"						"10"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_size_16"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Size_14"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Size_18"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Size_18"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"use_proportional_insets"			"1"
						"labelText"							"18"
						"auto_wide_tocontents"				"1"
						"auto_tall_tocontents"				"1"
						"font"								"HudFontSmallBold"
						"textinsetx"						"10"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_size_18"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Size_16"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Size_20"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Size_20"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"use_proportional_insets"			"1"
						"labelText"							"20"
						"auto_wide_tocontents"				"1"
						"auto_tall_tocontents"				"1"
						"font"								"HudFontSmallBold"
						"textinsetx"						"10"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_size_20"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Size_18"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Size_22"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Size_22"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"use_proportional_insets"			"1"
						"labelText"							"22"
						"auto_wide_tocontents"				"1"
						"auto_tall_tocontents"				"1"
						"font"								"HudFontSmallBold"
						"textinsetx"						"10"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_size_22"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Size_20"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Size_24"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Size_24"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"use_proportional_insets"			"1"
						"labelText"							"24"
						"auto_wide_tocontents"				"1"
						"auto_tall_tocontents"				"1"
						"font"								"HudFontSmallBold"
						"textinsetx"						"10"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_size_24"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Size_22"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Size_26"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Size_26"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"use_proportional_insets"			"1"
						"labelText"							"26"
						"auto_wide_tocontents"				"1"
						"auto_tall_tocontents"				"1"
						"font"								"HudFontSmallBold"
						"textinsetx"						"10"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_size_26"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Size_24"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Size_28"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Size_28"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"use_proportional_insets"			"1"
						"labelText"							"28"
						"auto_wide_tocontents"				"1"
						"auto_tall_tocontents"				"1"
						"font"								"HudFontSmallBold"
						"textinsetx"						"10"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_size_28"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Size_26"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
				}
			}
			"Color"
			{
				"ControlName"				"EditablePanel"
				"fieldName"					"Color"
				"xpos"						"-7"
				"ypos"						"10"
				"zpos"						"50"
				"wide"						"90"
				"tall"						"115"
				"visible"					"1"
				"enabled"					"1"
				"proportionaltoparent"		"1"

				"pin_to_sibling"		"On"
				"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"zpos"						"10"
					"wide"						"0"
					"tall"						"15"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Gen_Color"
					"font"						"HudFontSmallBold"
					"auto_wide_tocontents"		"1"
					"use_proportional_insets"	"1"
					"proportionaltoparent"		"1"
				}

				"Restart"
				{
					"ControlName"	"ImagePanel"
					"fieldName"		"Restart"
					"xpos"			"5"
					"ypos"			"0"
					"zpos"			"7"
					"wide"			"15"
					"tall"			"15"
					"visible"		"1"
					"enabled"		"1"
					"image"			"replay/thumbnails/menu/glyph/refresh"
					"drawcolor"		"TanLight"
					"scaleImage"	"1"

					"pin_to_sibling"	"Title"
					"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
					"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
				}

				"Options"
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"Options"
					"xpos"							"0"
					"ypos"							"20"
					"zpos"							"20"
					"wide"							"f0"
					"tall"							"95"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintbackground"				"0"
					"paintBackgroundType"			"0"

					"Color_Black"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Black"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_black"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairBlack"
						"armedbgcolor_override"				"CrosshairBlackHover"
					}
					"Color_White"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_White"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_white"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairWhite"
						"armedbgcolor_override"				"CrosshairWhiteHover"

						"pin_to_sibling"					"Color_Black"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Color_LGrey"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_LGrey"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_lgrey"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairLGrey"
						"armedbgcolor_override"				"CrosshairLGreyHover"

						"pin_to_sibling"					"Color_White"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Color_Grey"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Grey"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_grey"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairGrey"
						"armedbgcolor_override"				"CrosshairGreyHover"

						"pin_to_sibling"					"Color_LGrey"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}


					"Color_Violet"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Violet"
						"xpos"								"0"
						"ypos"								"2"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_violet"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairViolet"
						"armedbgcolor_override"				"CrosshairVioletHover"
	
						"pin_to_sibling"					"Color_Black"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"
					}
					"Color_Pink"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Pink"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_pink"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairPink"
						"armedbgcolor_override"				"CrosshairPinkHover"

						"pin_to_sibling"					"Color_Violet"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Color_Magenta"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Magenta"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_magenta"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairMagenta"
						"armedbgcolor_override"				"CrosshairMagentaHover"

						"pin_to_sibling"					"Color_Pink"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Color_Purple"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Purple"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_purple"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairPurple"
						"armedbgcolor_override"				"CrosshairPurpleHover"

						"pin_to_sibling"					"Color_Magenta"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}


					"Color_Orange"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Orange"
						"xpos"								"0"
						"ypos"								"2"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_orange"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairOrange"
						"armedbgcolor_override"				"CrosshairOrangeHover"

						"pin_to_sibling"					"Color_Violet"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"
					}
					"Color_Yellow"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Yellow"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_yellow"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairYellow"
						"armedbgcolor_override"				"CrosshairYellowHover"

						"pin_to_sibling"					"Color_Orange"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Color_Red"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Red"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_red"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairRed"
						"armedbgcolor_override"				"CrosshairRedHover"

						"pin_to_sibling"					"Color_Yellow"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Color_RedDark"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_RedDark"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_reddark"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairRedDark"
						"armedbgcolor_override"				"CrosshairRedDarkHover"

						"pin_to_sibling"					"Color_Red"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}


					"Color_Blu"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Blu"
						"xpos"								"0"
						"ypos"								"2"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_blu"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairBlu"
						"armedbgcolor_override"				"CrosshairBluHover"

						"pin_to_sibling"					"Color_Orange"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"
					}					
					"Color_Cyan"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Cyan"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_cyan"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairCyan"
						"armedbgcolor_override"				"CrosshairCyanHover"

						"pin_to_sibling"					"Color_Blu"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}	
					"Color_Teal"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Teal"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_teal"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairTeal"
						"armedbgcolor_override"				"CrosshairTealHover"

						"pin_to_sibling"					"Color_Cyan"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Color_Blue"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Blue"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_blue"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairBlue"
						"armedbgcolor_override"				"CrosshairBlueHover"

						"pin_to_sibling"					"Color_Teal"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}


					"Color_GreenDark"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_GreenDark"
						"xpos"								"0"
						"ypos"								"2"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_greendark"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairGreenDark"
						"armedbgcolor_override"				"CrosshairGreenDarkHover"

						"pin_to_sibling"					"Color_Blu"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"
					}
					"Color_GreenMint"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_GreenMint"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_greenpale"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairGreenMint"
						"armedbgcolor_override"				"CrosshairGreenMintHover"

						"pin_to_sibling"					"Color_GreenDark"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Color_GreenPale"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_GreenPale"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_greenpale"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairGreenPale"
						"armedbgcolor_override"				"CrosshairGreenPaleHover"

						"pin_to_sibling"					"Color_GreenMint"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Color_Green"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Color_Green"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"20"
						"tall"								"17"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							""
						"command"							"engine hud_xhair_color_green"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"defaultbgcolor_override"			"CrosshairGreen"
						"armedbgcolor_override"				"CrosshairGreenHover"

						"pin_to_sibling"					"Color_GreenPale"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
				}
			}
			"Style"
			{
				"ControlName"				"EditablePanel"
				"fieldName"					"Style"
				"xpos"						"12"
				"ypos"						"0"
				"zpos"						"50"
				"wide"						"f0"
				"tall"						"120"
				"visible"					"1"
				"enabled"					"1"
				"proportionaltoparent"		"1"

				"pin_to_sibling"		"Color"
				"pin_to_sibling_corner"	"PIN_TOPRIGHT"

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"0"
					"ypos"						"0"
					"zpos"						"10"
					"wide"						"0"
					"tall"						"15"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Gen_Style"
					"font"						"HudFontSmallBold"
					"auto_wide_tocontents"		"1"
					"use_proportional_insets"	"1"
					"proportionaltoparent"		"1"
				}

				"Options"
				{
					"ControlName"					"EditablePanel"
					"fieldName"						"Options"
					"xpos"							"0"
					"ypos"							"20"
					"zpos"							"20"
					"wide"							"f15"
					"tall"							"130"
					"visible"						"1"
					"enabled"						"1"
					"proportionaltoparent"			"1"
					"paintbackground"				"0"
					"paintBackgroundType"			"0"

					"pin_to_sibling"				"Separator"
					"pin_corner_to_sibling"			"PIN_CENTER_TOP"
					"pin_to_sibling_corner"			"PIN_CENTER_BOTTOM"

					"Crosshair_1"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_1"
						"xpos"								"0"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"						
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"!"

						"use_proportional_insets"			"1"						
						"textinsetx"						"4"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_1"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"
					}
					"Crosshair_2"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_2"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"						
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"#"

						"use_proportional_insets"			"1"						
						"textinsetx"						"4"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_2"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_1"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_3"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_3"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"$"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_3"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"
	
						"pin_to_sibling"					"Crosshair_2"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_4"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_4"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"%"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_4"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_3"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_5"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_5"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"'"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_5"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_4"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_6"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_6"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"("

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_6"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_5"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_7"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_7"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							")"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_7"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_6"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_8"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_8"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"*"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_8"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_7"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_9"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_9"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"+"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_9"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_8"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_10"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_10"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							","

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_10"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_9"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_11"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_11"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"-"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_11"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_10"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_12"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_12"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"."

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_12"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_11"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_13"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_13"
						"xpos"								"0"
						"ypos"								"2"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"/"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_13"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_1"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"
					}
					"Crosshair_14"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_14"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"0"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_14"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_13"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_15"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_15"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"1"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_15"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_14"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_16"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_16"
						"xpos"								"0"
						"ypos"								"2"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"2"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_16"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_1"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"
					}
					"Crosshair_17"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_17"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"3"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_17"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_16"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_18"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_18"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"4"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_18"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_17"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_19"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_19"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"5"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_19"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_18"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_20"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_20"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"6"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_20"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_19"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_21"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_21"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"7"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_21"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_20"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_22"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_22"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"8"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_22"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_21"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_23"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_23"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"9"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_23"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_22"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_24"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_24"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							":"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_24"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_23"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_25"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_25"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"<"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_25"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_24"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_26"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_26"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"="

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_26"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_25"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_27"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_27"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							">"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_27"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_26"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_28"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_28"
						"xpos"								"0"
						"ypos"								"2"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"?"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_28"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_13"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"
					}
					"Crosshair_29"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_29"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"@"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_29"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_28"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_30"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_30"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"A"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_30"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_29"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_31"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_31"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"B"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_31"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_30"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_32"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_32"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"C"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_32"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_31"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_33"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_33"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"D"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_33"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_32"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_34"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_34"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"E"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_34"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_33"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_35"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_35"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"F"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_35"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_34"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_36"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_36"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"G"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_36"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_35"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_37"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_37"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"H"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_37"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_36"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_38"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_38"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"I"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_38"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_37"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_39"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_39"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"J"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_39"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_38"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_40"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_40"
						"xpos"								"0"
						"ypos"								"2"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"K"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_40"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_28"
						"pin_to_sibling_corner"				"PIN_BOTTOMLEFT"
					}
					"Crosshair_41"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_41"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"L"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_41"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_40"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_42"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_42"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"M"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_42"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_41"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_43"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_43"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"N"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_43"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_42"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_44"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_44"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"O"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_44"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_43"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
					"Crosshair_45"
					{
						"ControlName"						"CExButton"
						"fieldName"							"Crosshair_45"
						"xpos"								"2"
						"ypos"								"0"
						"zpos"								"20"
						"wide"								"22"
						"tall"								"o1"
						"visible"							"1"
						"enabled"							"1"
						"proportionaltoparent"				"1"
						"labelText"							"P"

						"use_proportional_insets"			"1"
						"textinsetx"						"2"
						"font"								"Size-20"
						"textAlignment"						"center"
						"command"							"engine hud_xhair_style_45"
						"actionsignallevel"					"7"
						"sound_depressed"					"UI/buttonclick.wav"

						"pin_to_sibling"					"Crosshair_44"
						"pin_to_sibling_corner"				"PIN_TOPRIGHT"
					}
				}
			}

		}
	}
	}
	}
}