"_customizations/hud_customization_damage.res"
{
	"SafeMode"
	{
		"CustomizationPanel"
		{
			"CustomizationPanelDamage"
			{
				"ControlName"			"CScrollableList"
				"fieldName"				"CustomizationPanelDamage"
				"wide"					"f0"
				"tall"					"f0"
				"visible"				"0"
				"enabled"				"1"
				"proportionaltoparent"	"1"

				"Scrollbar"
				{
					"xpos"					"rs1+1"
					"wide"					"6"
					"tall"					"f0"
					"zpos"					"1000"
					"proportionaltoparent"	"1"

					"Slider"
					{
						"paintBackgroundType"	"0"
						"fgcolor_override"		"Gray"
					}

					"nobuttons"				"1"
				}

				"DamageTitle"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"DamageTitle"
					"xpos"						"cs-0.5"
					"ypos"						"8"
					"wide"						"f30"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Cat_Damage"
					"font"						"HudFontMediumBold"
					"textAlignment"				"west"
					"fgcolor"					"White"
					"proportionaltoparent"		"1"
				}				
				
				"DamageInfo"
				{
					"ControlName"	"CExImageButton"
					"fieldName"		"DamageInfo"
					"xpos"			"rs1-20"
					"ypos"			"15"
					"zpos"			"7"
					"wide"			"15"
					"tall"			"15"
					"visible"		"1"
					"enabled"		"1"
					"labelText"		""
					"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Damage"
					"paintBackground"	"0"
					"proportionaltoparent"		"1"
					"sound_depressed"	"UI/buttonclick.wav"
					"sound_released"	"UI/buttonclickrelease.wav"

					"image_drawcolor"	"255 255 255 255"
					"image_armedcolor"	"200 200 200 255"
			
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"zpos"			"1"
						"wide"			"f0"
						"tall"			"f0"
						"visible"		"1"
						"enabled"		"1"
						"image"			"info"
						"scaleImage"	"1"
						"proportionaltoparent"	"1"
					}
				}

				"Options"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"Options"
					"xpos"						"cs-0.5"
					"ypos"						"40"	
					"zpos"						"20"
					"wide"						"f20"
					"tall"						"435"
					"visible"					"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"

					"LastDamageDoneTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"LastDamageDoneTitle"
						"xpos"						"cs-0.5"
						"ypos"						"0"
						"wide"						"f10"
						"tall"						"25"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Damage_LDD_Title"
						"font"						"HudFontSmallBold"
						"textinsetx"				"10"
						"textinsety"				"0.5"	
						"textAlignment"				"west"
						"fgcolor"					"White"
						"bgcolor_override"			"StoreGreen"
						"paintBackground"			"1"
						"paintBackgroundType"		"2"
						"roundedcorners"			"3"
						"use_proportional_insets"	"1"
						"proportionaltoparent"		"1"
					}

					"LastDamageDoneInfo"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"LastDamageDoneInfo"
						"xpos"			"-5"
						"ypos"			"-5"
						"zpos"			"7"
						"wide"			"15"
						"tall"			"15"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		""
						"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Last-Damage-Done"
						"paintBackground"	"0"
						"sound_depressed"	"UI/buttonclick.wav"
						"sound_released"	"UI/buttonclickrelease.wav"

						"pin_to_sibling"	"LastDamageDoneTitle"
						"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						"pin_corner_to_sibling"	"PIN_TOPRIGHT"

						"image_drawcolor"	"255 255 255 255"
						"image_armedcolor"	"200 200 200 255"
				
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"cs-0.5"
							"ypos"			"cs-0.5"
							"zpos"			"1"
							"wide"			"f0"
							"tall"			"f0"
							"visible"		"1"
							"enabled"		"1"
							"image"			"info"
							"scaleImage"	"1"
							"proportionaltoparent"	"1"
						}
					}

					"LastDamageDoneSeparator"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LastDamageDoneSeparator"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"f10"
						"tall"						"2"
						"visible"					"1"
						"enabled"					"1"
						"paintBackgroundtype"		"0"
						"bgcolor_override"			"TanDark"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"LastDamageDoneTitle"
						"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
						"pin_corner_to_sibling"		"PIN_CENTER_TOP"
					}

					"LastDamageDoneOn"
					{
						"ControlName"					"CExButton"
						"fieldName"						"LastDamageDoneOn"
						"xpos"							"-5"
						"ypos"							"8"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Enabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"LastDamageDoneSeparator"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"LastDamageDoneOff"
					{
						"ControlName"					"CExButton"
						"fieldName"						"LastDamageDoneOff"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Disabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"LastDamageDoneOn"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"
					}

					"LastDamageDonePositionSubTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"LastDamageDonePositionSubTitle"
						"xpos"						"0"
						"ypos"						"6"
						"wide"						"f25"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Gen_Position"
						"font"						"HudFontSmallestBold"
						"textAlignment"				"west"
						"fgcolor"					"Gray"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"LastDamageDoneOn"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"		
					}
					"LastDamageDoneAmmo"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LastDamageDoneAmmo"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"110"
						"tall"						"o0.8"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"LastDamageDonePositionSubTitle"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_ammo"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f18"
							"tall"						"f18"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"
							"paintBackgroundType"		"2"
							"roundedcorners"			"11"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel_wide"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5-8"
								"ypos"				"6"
								"zpos"				"3"
								"wide"				"60"
								"tall"				"26"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"west"
								"font"				"HudFontMediumOutline"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}
	
							"AmmoImage"
							{
								"ControlName"	"CTFImagePanel"
								"fieldName"		"AmmoImage"
								"xpos"			"cs-0.5"
								"ypos"			"rs1-2"
								"zpos"			"2"
								"wide"			"75"
								"tall"			"o0.5"
								"visible"		"1"
								"image"			"../hud/ammo_blue_bg"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}
						}
					}		
					"LastDamageDoneHealth"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LastDamageDoneHealth"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"110"
						"tall"						"o0.8"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"LastDamageDoneAmmo"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_health"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f18"
							"tall"						"f18"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel_wide"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5-8"
								"ypos"				"6"
								"zpos"				"3"
								"wide"				"60"
								"tall"				"26"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"west"
								"font"				"HudFontMediumOutline"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}

							"HealthImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"HealthImage"
								"xpos"			"rs1-8"
								"ypos"			"rs1-6"
								"zpos"			"3"
								"wide"			"38"
								"tall"			"o1"
								"visible"		"1"
								"image"			"../hud/health_color"
								"scaleImage"	"1"
								"proportionaltoparent"	"1"
							}		
							"HealthImageBG"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"HealthImageBG"
								"xpos"			"rs1-6"
								"ypos"			"rs1-4"
								"zpos"			"2"
								"wide"			"42"
								"tall"			"o1"
								"visible"		"1"
								"image"			"../hud/health_bg"
								"scaleImage"	"1"
								"proportionaltoparent"	"1"
							}
						}
					}			
					
					"LastDamageDoneFontSubTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"LastDamageDoneFontSubTitle"
						"xpos"						"0"
						"ypos"						"4"
						"wide"						"f25"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Gen_Font"
						"font"						"HudFontSmallestBold"
						"textAlignment"				"west"
						"fgcolor"					"Gray"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"LastDamageDoneAmmo"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
					}
					"LastDamageDoneFontSecondary"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LastDamageDoneFontSecondary"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"LastDamageDoneFontSubTitle"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_health"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5"
								"ypos"				"cs-0.5"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f0"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"center"
								"font"				"HudFontMediumOutline"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
					"LastDamageDoneFontBold"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LastDamageDoneFontBold"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"LastDamageDoneFontSecondary"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_ammo"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"
							"paintBackgroundType"		"2"
							"roundedcorners"			"11"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5"
								"ypos"				"cs-0.5"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f0"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"center"
								"font"				"HudFontMediumBoldOutline"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
					"LastDamageDoneFontSecondaryNoOutline"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LastDamageDoneFontSecondaryNoOutline"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"LastDamageDoneFontBold"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_health"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5"
								"ypos"				"cs-0.5"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f0"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"center"
								"font"				"HudFontMedium"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
					"LastDamageDoneFontBoldNoOutline"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LastDamageDoneFontBoldNoOutline"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"LastDamageDoneFontSecondaryNoOutline"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_ammo"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"
							"paintBackgroundType"		"2"
							"roundedcorners"			"11"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5"
								"ypos"				"cs-0.5"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f0"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"center"
								"font"				"HudFontMediumBold"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}

					"FloatingDamageTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"FloatingDamageTitle"
						"xpos"						"cs-0.5"
						"ypos"						"270"
						"wide"						"f10"
						"tall"						"25"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Damage_FD_Title"
						"font"						"HudFontSmallBold"
						"textinsetx"				"10"
						"textinsety"				"0.5"	
						"textAlignment"				"west"
						"fgcolor"					"White"
						"bgcolor_override"			"StoreGreen"
						"paintBackground"			"1"
						"paintBackgroundType"		"2"
						"roundedcorners"			"3"
						"use_proportional_insets"	"1"
						"proportionaltoparent"		"1"
					}

					"FloatingDamageInfo"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"FloatingDamageInfo"
						"xpos"			"-5"
						"ypos"			"-5"
						"zpos"			"7"
						"wide"			"15"
						"tall"			"15"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		""
						"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Floating-Damage"
						"paintBackground"	"0"
						"sound_depressed"	"UI/buttonclick.wav"
						"sound_released"	"UI/buttonclickrelease.wav"

						"pin_to_sibling"	"FloatingDamageTitle"
						"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						"pin_corner_to_sibling"	"PIN_TOPRIGHT"

						"image_drawcolor"	"255 255 255 255"
						"image_armedcolor"	"200 200 200 255"
				
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"cs-0.5"
							"ypos"			"cs-0.5"
							"zpos"			"1"
							"wide"			"f0"
							"tall"			"f0"
							"visible"		"1"
							"enabled"		"1"
							"image"			"info"
							"scaleImage"	"1"
							"proportionaltoparent"	"1"
						}
					}

					"FloatingDamageSeparator"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"FloatingDamageSeparator"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"f10"
						"tall"						"2"
						"visible"					"1"
						"enabled"					"1"
						"paintBackgroundtype"		"0"
						"bgcolor_override"			"TanDark"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"FloatingDamageTitle"
						"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
						"pin_corner_to_sibling"		"PIN_CENTER_TOP"
					}

					"FloatingDamageOn"
					{
						"ControlName"					"CExButton"
						"fieldName"						"FloatingDamageOn"
						"xpos"							"-5"
						"ypos"							"8"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Enabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"FloatingDamageSeparator"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"FloatingDamageOff"
					{
						"ControlName"					"CExButton"
						"fieldName"						"FloatingDamageOff"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Disabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"FloatingDamageOn"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"
					}

					"FloatingDamageFontSubTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"FloatingDamageFontSubTitle"
						"xpos"						"0"
						"ypos"						"6"
						"wide"						"f25"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Gen_Font"
						"font"						"HudFontSmallestBold"
						"textAlignment"				"west"
						"fgcolor"					"Gray"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"FloatingDamageOn"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
					}
					"FloatingDamageFontSecondary"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"FloatingDamageFontSecondary"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"FloatingDamageFontSubTitle"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_health"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel_chara"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5"
								"ypos"				"0"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f22"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"center"
								"font"				"HudFontMediumOutline"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
					"FloatingDamageFontBold"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"FloatingDamageFontBold"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"FloatingDamageFontSecondary"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_ammo"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"
							"paintBackgroundType"		"2"
							"roundedcorners"			"11"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel_chara"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5"
								"ypos"				"0"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f22"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"center"
								"font"				"HudFontMediumBoldOutline"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
					"FloatingDamageFontSecondaryNoOutline"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"FloatingDamageFontSecondaryNoOutline"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"FloatingDamageFontBold"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_health"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel_chara"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5"
								"ypos"				"0"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f22"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"center"
								"font"				"HudFontMedium"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
					"FloatingDamageFontBoldNoOutline"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"FloatingDamageFontBoldNoOutline"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"FloatingDamageFontSecondaryNoOutline"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_ammo"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"
							"paintBackgroundType"		"2"	
							"roundedcorners"			"15"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"-2"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel_chara"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"DamageValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"DamageValue"
								"xpos"				"cs-0.5"
								"ypos"				"0"
								"zpos"				"-1"
								"wide"				"f0"
								"tall"				"f22"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_NegValue"
								"textAlignment"		"center"
								"font"				"HudFontMediumBold"
								"fgcolor"			"255 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
				}
			}
		}
	}
}