"resource/ui/customizations/#customization_menu/hud_customization_folder.res"
{
	"SafeMode"
	{
		"Folder_Name_Warning"
		{
			"ControlName"								"EditablePanel"
			"fieldName"									"Folder_Name_Warning"
			"xpos"										"cs-0.5"
			"ypos"										"cs-0.5-1"
			"zpos"										"999"
			"wide"										"f5"
			"tall"										"228"
			"visible"									"1"
			"enabled"									"1"
			"proportionaltoparent"						"1"
			"paintBackground"							"1"
			"paintBackgroundtype"						"0"
			"bgcolor_override"							"TanDarker"

			"Warning"
			{
				"ControlName"							"CExLabel"
				"fieldName"								"Warning"
				"xpos"									"cs-0.5"
				"ypos"									"35"
				"zpos"									"0"
				"wide"									"f20"
				"tall"									"50"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"labelText"								"#CenHud_Foldercheck_Warning"
				"font"									"HudFontGiantBold"
				"textAlignment"							"center"
				"fgcolor"								"TeamRed"
			}
			"Explanation_1"
			{
				"ControlName"							"CExLabel"
				"fieldName"								"Explanation_1"
				"xpos"									"0"
				"ypos"									"0"
				"zpos"									"0"
				"wide"									"f20"
				"tall"									"0"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"labelText"								"#CenHud_Foldercheck_Part1"
				"font"									"HudFontSmall"
				"textAlignment"							"center"
				"fgcolor"								"Gray"
				"auto_tall_tocontents"					"1"

				"pin_to_sibling"						"Warning"
				"pin_to_sibling_corner"					"PIN_BOTTOMLEFT"
			}
			"center-hud"
			{
				"ControlName"							"CExLabel"
				"fieldName"								"center-hud"
				"xpos"									"0"
				"ypos"									"5"
				"zpos"									"0"
				"wide"									"f20"
				"tall"									"25"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"labelText"								"center-hud"
				"font"									"HudFontGiantSecondary"
				"textAlignment"							"center"
				"fgcolor"								"White"

				"pin_to_sibling"						"Explanation_1"
				"pin_to_sibling_corner"					"PIN_BOTTOMLEFT"
			}
			"Explanation_2"
			{
				"ControlName"							"CExLabel"
				"fieldName"								"Explanation_2"
				"xpos"									"0"
				"ypos"									"10"
				"zpos"									"0"
				"wide"									"f20"
				"tall"									"0"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"Wrap"									"1"
				"CenterWrap"							"1"
				"labelText"								"#CenHud_Foldercheck_Part2"
				"font"									"HudFontSmall"
				"textAlignment"							"center"
				"fgcolor"								"Gray"
				"auto_tall_tocontents"					"1"

				"pin_to_sibling"						"center-hud"
				"pin_to_sibling_corner"					"PIN_BOTTOMLEFT"
			}
		}
	}
}