// TODO: Maybe make the customization tabs (last damage, floating damage) dropdown menus?
// https://discord.com/channels/673304949718908948/687351019637702731/1269914728059375698
// https://codeberg.org/RoseyLemonz/center-hud/src/branch/main/%23dev/mainmenuoverride_dev.res
//
// Also, redo the title to make it so that the info icon can be next to the label

"_customizations/hud_customization_damage.res"
{
	"SafeMode"
	{
		"CustomizationPanel"
		{
			"CustomizationPanelDamage"
			{
				"ControlName"			"CScrollableList"
				"fieldName"				"CustomizationPanelDamage"
				"wide"					"f0"
				"tall"					"f0"
				"visible"				"0"
				"enabled"				"1"
				"proportionaltoparent"	"1"

				"Scrollbar"
				{
					"xpos"					"rs1+1"
					"wide"					"6"
					"tall"					"f0"
					"zpos"					"1000"
					"proportionaltoparent"	"1"

					"Slider"
					{
						"paintBackgroundType"	"0"
						"fgcolor_override"		"Gray"
					}

					"nobuttons"				"1"
				}

				"Title"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"Title"
					"xpos"						"cs-0.5"
					"ypos"						"8"
					"wide"						"f30"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Cat_Damage"
					"font"						"HudFontMediumBold"
					"textAlignment"				"west"
					"fgcolor"					"White"
					"proportionaltoparent"		"1"
				}				
				
				"Info"
				{
					"ControlName"	"CExImageButton"
					"fieldName"		"Info"
					"xpos"			"rs1-20"
					"ypos"			"15"
					"zpos"			"7"
					"wide"			"15"
					"tall"			"15"
					"visible"		"1"
					"enabled"		"1"
					"labelText"		""
					"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Damage"
					"paintBackground"	"0"
					"proportionaltoparent"		"1"
					"sound_depressed"	"UI/buttonclick.wav"
					"sound_released"	"UI/buttonclickrelease.wav"

					"image_drawcolor"	"255 255 255 255"
					"image_armedcolor"	"200 200 200 255"
			
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"zpos"			"1"
						"wide"			"f0"
						"tall"			"f0"
						"visible"		"1"
						"enabled"		"1"
						"image"			"info"
						"scaleImage"	"1"
						"proportionaltoparent"	"1"
					}
				}

				"Options"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"Options"
					"xpos"						"cs-0.5"
					"ypos"						"40"	
					"zpos"						"20"
					"wide"						"f20"
					"tall"						"295"
					"visible"					"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"

					"LDDTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"LDDTitle"
						"xpos"						"cs-0.5"
						"ypos"						"0"
						"wide"						"f10"
						"tall"						"25"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Damage_LDD_Title"
						"font"						"HudFontSmallBold"
						"textinsetx"				"10"
						"textinsety"				"0.5"	
						"textAlignment"				"west"
						"fgcolor"					"White"
						"bgcolor_override"			"StoreGreen"
						"paintBackground"			"1"
						"paintBackgroundType"		"2"
						"roundedcorners"			"3"
						"use_proportional_insets"	"1"
						"proportionaltoparent"		"1"
					}

					"LDDInfo"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"LDDInfo"
						"xpos"			"-5"
						"ypos"			"-5"
						"zpos"			"7"
						"wide"			"15"
						"tall"			"15"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		""
						"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Customizations#Last-Damage-Done"
						"paintBackground"	"0"
						"sound_depressed"	"UI/buttonclick.wav"
						"sound_released"	"UI/buttonclickrelease.wav"

						"pin_to_sibling"	"LDDTitle"
						"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						"pin_corner_to_sibling"	"PIN_TOPRIGHT"

						"image_drawcolor"	"255 255 255 255"
						"image_armedcolor"	"200 200 200 255"
				
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"cs-0.5"
							"ypos"			"cs-0.5"
							"zpos"			"1"
							"wide"			"f0"
							"tall"			"f0"
							"visible"		"1"
							"enabled"		"1"
							"image"			"info"
							"scaleImage"	"1"
							"proportionaltoparent"	"1"
						}
					}

					"LDDSeparator"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LDDSeparator"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"f10"
						"tall"						"2"
						"visible"					"1"
						"enabled"					"1"
						"paintBackgroundtype"		"0"
						"bgcolor_override"			"TanDark"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"LDDTitle"
						"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
						"pin_corner_to_sibling"		"PIN_CENTER_TOP"
					}

					"LDDOn"
					{
						"ControlName"					"CExButton"
						"fieldName"						"LDDOn"
						"xpos"							"-5"
						"ypos"							"8"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Enabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"LDDSeparator"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"LDDOff"
					{
						"ControlName"					"CExButton"
						"fieldName"						"LDDOff"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Disabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"LDDOn"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"
					}

					"LDDPosSubTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"LDDPosSubTitle"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"f25"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Gen_Position"
						"font"						"HudFontSmallestBold"
						"textAlignment"				"west"
						"fgcolor"					"Gray"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"LDDOn"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
					}
					"LDDPosOption"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LDDPosOption"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"f0"
						"tall"						"25"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"LDDPosSubTitle"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

						"LDDPosAmmo"
						{
							"ControlName"					"CExButton"
							"fieldName"						"LDDPosAmmo"
							"xpos"							"0"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"25"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Damage_LDD_Ammo"
							"textAlignment"					"center"
							"font"							"HudFontSmallBold"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"LDDPosHealth"
						{
							"ControlName"					"CExButton"
							"fieldName"						"LDDPosHealth"
							"xpos"							"5"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"25"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Damage_LDD_Health"
							"textAlignment"					"center"
							"font"							"HudFontSmallBold"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"pin_to_sibling"				"LDDPosAmmo"
							"pin_to_sibling_corner"			"PIN_TOPRIGHT"
						}
					}				
					
					"LDDFontSubTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"LDDFontSubTitle"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"f0"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Gen_Font"
						"font"						"HudFontSmallestBold"
						"textAlignment"				"west"
						"fgcolor"					"Gray"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"LDDPosOption"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
					}
					"LDDFontOption"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"LDDFontOption"
						"xpos"						"0"
						"ypos"						"0"
						"wide"						"f0"
						"tall"						"30"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"LDDFontSubTitle"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

						"LDDFont"
						{
							"ControlName"					"CExButton"
							"fieldName"						"LDDFont"
							"xpos"							"0"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"30"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_NegValue"
							"textAlignment"					"center"
							"font"							"HudFontMediumOutline"
							"textinsetx"					"25"
							"textinsety"					"2"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultfgcolor_override"		"255 255 0 255"
							"armedfgcolor_override"			"255 255 0 255"
							"depressedfgcolor_override"		"255 255 0 255"
						}

						"LDDFontBold"
						{
							"ControlName"					"CExButton"
							"fieldName"						"LDDFontBold"
							"xpos"							"5"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"30"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_NegValue"
							"textAlignment"					"center"
							"font"							"HudFontMediumBoldOutline"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultfgcolor_override"		"255 255 0 255"
							"armedfgcolor_override"			"255 255 0 255"
							"depressedfgcolor_override"		"255 255 0 255"

							"pin_to_sibling"	"LDDFont"
							"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						}

						"LDDFontNoutline"
						{
							"ControlName"					"CExButton"
							"fieldName"						"LDDFontNoutline"
							"xpos"							"5"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"30"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_NegValue"
							"textAlignment"					"center"
							"font"							"HudFontMedium"
							"textinsetx"					"25"
							"textinsety"					"2"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultfgcolor_override"		"255 255 0 255"
							"armedfgcolor_override"			"255 255 0 255"
							"depressedfgcolor_override"		"255 255 0 255"

							"pin_to_sibling"	"LDDFontBold"
							"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						}
						"LDDFontNoutlineBold"
						{
							"ControlName"					"CExButton"
							"fieldName"						"LDDFontNoutlineBold"
							"xpos"							"5"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"30"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_NegValue"
							"textAlignment"					"center"
							"font"							"HudFontMediumBold"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultfgcolor_override"		"255 255 0 255"
							"armedfgcolor_override"			"255 255 0 255"
							"depressedfgcolor_override"		"255 255 0 255"

							"pin_to_sibling"	"LDDFontNoutline"
							"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						}
					}

					"FDTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"FDTitle"
						"xpos"						"cs-0.5"
						"ypos"						"170"
						"wide"						"f10"
						"tall"						"25"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Damage_FD_Title"
						"font"						"HudFontSmallBold"
						"textinsetx"				"10"
						"textinsety"				"0.5"	
						"textAlignment"				"west"
						"fgcolor"					"White"
						"bgcolor_override"			"StoreGreen"
						"paintBackground"			"1"
						"paintBackgroundType"		"2"
						"roundedcorners"			"3"
						"use_proportional_insets"	"1"
						"proportionaltoparent"		"1"
					}

					"FDInfo"
					{
						"ControlName"	"CExImageButton"
						"fieldName"		"FDInfo"
						"xpos"			"-5"
						"ypos"			"-5"
						"zpos"			"7"
						"wide"			"15"
						"tall"			"15"
						"visible"		"1"
						"enabled"		"1"
						"labelText"		""
						"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Floating-Damage"
						"paintBackground"	"0"
						"sound_depressed"	"UI/buttonclick.wav"
						"sound_released"	"UI/buttonclickrelease.wav"

						"pin_to_sibling"	"FDTitle"
						"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						"pin_corner_to_sibling"	"PIN_TOPRIGHT"

						"image_drawcolor"	"255 255 255 255"
						"image_armedcolor"	"200 200 200 255"
				
						"SubImage"
						{
							"ControlName"	"ImagePanel"
							"fieldName"		"SubImage"
							"xpos"			"cs-0.5"
							"ypos"			"cs-0.5"
							"zpos"			"1"
							"wide"			"f0"
							"tall"			"f0"
							"visible"		"1"
							"enabled"		"1"
							"image"			"info"
							"scaleImage"	"1"
							"proportionaltoparent"	"1"
						}
					}

					"FDSeparator"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"FDSeparator"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"f10"
						"tall"						"2"
						"visible"					"1"
						"enabled"					"1"
						"paintBackgroundtype"		"0"
						"bgcolor_override"			"TanDark"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"FDTitle"
						"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
						"pin_corner_to_sibling"		"PIN_CENTER_TOP"
					}

					"FDOn"
					{
						"ControlName"					"CExButton"
						"fieldName"						"FDOn"
						"xpos"							"-5"
						"ypos"							"8"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Enabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"FDSeparator"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"FDOff"
					{
						"ControlName"					"CExButton"
						"fieldName"						"FDOff"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Disabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"FDOn"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"
					}

					"FDFontSubTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"FDFontSubTitle"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"f0"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Gen_Font"
						"font"						"HudFontSmallestBold"
						"textAlignment"				"west"
						"fgcolor"					"Gray"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"FDOn"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
					}
					"FDFontOption"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"FDFontOption"
						"xpos"						"0"
						"ypos"						"0"
						"wide"						"f0"
						"tall"						"30"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"FDFontSubTitle"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

						"FDFont"
						{
							"ControlName"					"CExButton"
							"fieldName"						"FDFont"
							"xpos"							"0"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"30"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_NegValue"
							"textAlignment"					"center"
							"font"							"HudFontMediumOutline"
							"textinsetx"					"25"
							"textinsety"					"2"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultfgcolor_override"		"255 255 0 255"
							"armedfgcolor_override"			"255 255 0 255"
							"depressedfgcolor_override"		"255 255 0 255"
						}

						"FDFontBold"
						{
							"ControlName"					"CExButton"
							"fieldName"						"FDFontBold"
							"xpos"							"5"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"30"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_NegValue"
							"textAlignment"					"center"
							"font"							"HudFontMediumBoldOutline"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultfgcolor_override"		"255 255 0 255"
							"armedfgcolor_override"			"255 255 0 255"
							"depressedfgcolor_override"		"255 255 0 255"

							"pin_to_sibling"	"FDFont"
							"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						}

						"FDFontNoutline"
						{
							"ControlName"					"CExButton"
							"fieldName"						"FDFontNoutline"
							"xpos"							"5"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"30"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_NegValue"
							"textAlignment"					"center"
							"font"							"HudFontMedium"
							"textinsetx"					"25"
							"textinsety"					"2"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultfgcolor_override"		"255 255 0 255"
							"armedfgcolor_override"			"255 255 0 255"
							"depressedfgcolor_override"		"255 255 0 255"

							"pin_to_sibling"	"FDFontBold"
							"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						}
						"FDFontNoutlineBold"
						{
							"ControlName"					"CExButton"
							"fieldName"						"FDFontNoutlineBold"
							"xpos"							"5"
							"ypos"							"0"
							"zpos"							"5"
							"wide"							"0"
							"tall"							"30"
							"visible"						"1"
							"enabled"						"1"
							"allcaps"						"1"
							"labelText"						"#CenHud_Custom_Gen_NegValue"
							"textAlignment"					"center"
							"font"							"HudFontMediumBold"
							"textinsetx"					"25"
							"command"						""
							"actionsignallevel"				"6"
							"auto_wide_tocontents"			"1"
							"proportionaltoparent"			"1"
							"use_proportional_insets"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultfgcolor_override"		"255 255 0 255"
							"armedfgcolor_override"			"255 255 0 255"
							"depressedfgcolor_override"		"255 255 0 255"

							"pin_to_sibling"	"FDFontNoutline"
							"pin_to_sibling_corner"	"PIN_TOPRIGHT"
						}
					}
				}
			}
		}
	}
}