"resource/ui/customizations/#customization_menu/hud_customization_home.res"
{
	"SafeMode"
	{
		"CustomizationPanel"
		{
			"CustomizationPanelHome"
			{
				"ControlName"			"EditablePanel"
				"fieldName"				"CustomizationPanelHome"
				"wide"					"f0"
				"tall"					"f0"
				"visible"				"1"
				"enabled"				"1"
				"proportionaltoparent"	"1"

				"HomeTitle"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"HomeTitle"
					"xpos"						"15"
					"ypos"						"8"
					"wide"						"f30"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Desc_Welcome"
					"font"						"HudFontMediumBold"
					"textAlignment"				"west"
					"fgcolor"					"White"
					"proportionaltoparent"		"1"
					"use_proportional_insets"	"1"
				}
				"SelectACategory"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"SelectACategory"
					"xpos"						"16"
					"ypos"						"32"
					"wide"						"f32"
					"tall"						"15"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Desc_Category"
					"font"						"HudFontSmall"
					"textAlignment"				"west"
					"fgcolor"					"Gray"
					"proportionaltoparent"		"1"
					"use_proportional_insets"	"1"
				}
				"TitleSeparator"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"TitleSeparator"
					"xpos"						"10"
					"ypos"						"50"
					"wide"						"f20"
					"tall"						"2"
					"visible"					"1"
					"enabled"					"1"
					"paintBackgroundtype"		"3"
					"bgcolor_override"			"TanDark"
					"proportionaltoparent"		"1"
				}

				"RestartIcon"
				{
					"ControlName"				"ImagePanel"
					"fieldName"					"RestartIcon"
					"xpos"						"16"
					"ypos"						"65"
					"wide"						"20"
					"tall"						"o1"
					"visible"					"1"
					"enabled"					"1"
					"image"						"replay/thumbnails/menu/glyph/refresh"
					"drawcolor"					"TeamRed"
					"scaleImage"				"1"
					"proportionaltoparent"		"1"
				}
				"RestartMessage"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"RestartMessage"
					"xpos"						"45"
					"ypos"						"52"
					"wide"						"f55"
					"tall"						"50"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Desc_Warn_Restart"
					"font"						"HudFontSmaller"
					"fgcolor"					"TeamRed"
					"textAlignment"				"west"
					"fgcolor"					"White"
					"wrap"						"1"	
					"proportionaltoparent"		"1"
					"use_proportional_insets"	"1"
				}
				"RestartSeparator"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"RestartSeparator"
					"xpos"						"10"
					"ypos"						"102"
					"wide"						"f20"
					"tall"						"2"
					"visible"					"1"
					"enabled"					"1"
					"paintBackgroundtype"		"3"
					"bgcolor_override"			"TanDark"
					"proportionaltoparent"		"1"
				}

				"CTAIcon"
				{
					"ControlName"				"ImagePanel"
					"fieldName"					"CTAIcon"
					"xpos"						"14"
					"ypos"						"125"
					"wide"						"26"
					"tall"						"o1"
					"visible"					"1"
					"enabled"					"1"
					"image"						"replay/thumbnails/menu/glyph/repo"
					"drawcolor"					"QuestGold"
					"scaleImage"				"1"
					"proportionaltoparent"		"1"
				}
				"CTAMessage"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"CTAMessage"
					"xpos"						"45"
					"ypos"						"107"
					"wide"						"f55"
					"tall"						"65"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Desc_Contribute"
					"font"						"HudFontSmaller"
					"textAlignment"				"west"
					"fgcolor"					"White"
					"wrap"						"1"
					"proportionaltoparent"		"1"
					"use_proportional_insets"	"1"
				}
				"CTASeparator"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"CTASeparator"
					"xpos"						"10"
					"ypos"						"178"
					"wide"						"f20"
					"tall"						"2"
					"visible"					"1"
					"enabled"					"1"
					"paintBackgroundtype"		"3"
					"bgcolor_override"			"TanDark"
					"proportionaltoparent"		"1"
				}

				"BottomLinks"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"BottomLinks"
					"xpos"						"15"
					"ypos"						"183"
					"wide"						"0"
					"tall"						"16"
					"visible"					"1"
					"labelText"					"#CenHud_Desc_CallToAction"
					"font"						"HudFontSmallestBold"
					"textAlignment"				"west"
					"fgcolor"					"Gray"
					"auto_wide_tocontents"		"1"
					"proportionaltoparent"		"1"
				}
				"LinkGodeberg"
				{
					"ControlName"				"CExImageButton"
					"fieldName"					"LinkGodeberg"
					"xpos"						"5"
					"wide"						"16"
					"tall"						"o1"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					""
					"command"					"url https://codeberg.org/RoseyLemonz/center-hud"
					"paintBackground"			"0"
					"proportionaltoparent"		"1"

					"pin_to_sibling"			"BottomLinks"
					"pin_corner_to_sibling"		"PIN_TOPLEFT"
					"pin_to_sibling_corner"		"PIN_TOPRIGHT"

					"image_drawcolor"	"33 133 208 255"
					"image_armedcolor"	"13 93 198 255"
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"wide"			"f0"
						"tall"			"f0"
						"visible"		"1"
						"enabled"		"1"
						"scaleImage"	"1"
						"image"			"replay/thumbnails/menu/glyph/cberg"
						"proportionaltoparent"	"1"
					}			
				}
				"LinkGitHub"
				{
					"ControlName"				"CExImageButton"
					"fieldName"					"LinkGitHub"
					"xpos"						"5"
					"wide"						"16"
					"tall"						"o1"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					""
					"command"					"url https://github.com/RoseyLemonz/center-hud"
					"paintBackground"			"0"
					"proportionaltoparent"		"1"

					"pin_to_sibling"			"LinkGodeberg"
					"pin_corner_to_sibling"		"PIN_TOPLEFT"
					"pin_to_sibling_corner"		"PIN_TOPRIGHT"

					"image_drawcolor"	"255 255 255 255"
					"image_armedcolor"	"192 192 192 255"
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"wide"			"f0"
						"tall"			"f0"
						"visible"		"1"
						"enabled"		"1"
						"scaleImage"	"1"
						"image"			"replay/thumbnails/menu/glyph/ghub"
						"proportionaltoparent"	"1"
					}			
				}
				"LinkComfig"
				{
					"ControlName"				"CExImageButton"
					"fieldName"					"LinkComfig"
					"xpos"						"5"
					"wide"						"16"
					"tall"						"o1"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					""
					"command"					"url https://comfig.app/huds/page/center-hud/"
					"paintBackground"			"0"
					"proportionaltoparent"		"1"

					"pin_to_sibling"			"LinkGitHub"
					"pin_corner_to_sibling"		"PIN_TOPLEFT"
					"pin_to_sibling_corner"		"PIN_TOPRIGHT"

					"image_drawcolor"	"0 150 135 255"
					"image_armedcolor"	"0 100 90 255"
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"wide"			"f0"
						"tall"			"f0"
						"visible"		"1"
						"enabled"		"1"
						"scaleImage"	"1"
						"image"			"replay/thumbnails/menu/glyph/coms"
						"proportionaltoparent"	"1"
					}			
				}
				"LinkGB"
				{
					"ControlName"				"CExImageButton"
					"fieldName"					"LinkGB"
					"xpos"						"5"
					"wide"						"16"
					"tall"						"o1"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					""
					"command"					"url https://gamebanana.com/mods/485626"
					"paintBackground"			"0"
					"proportionaltoparent"		"1"

					"pin_to_sibling"			"LinkComfig"
					"pin_corner_to_sibling"		"PIN_TOPLEFT"
					"pin_to_sibling_corner"		"PIN_TOPRIGHT"

					"image_drawcolor"	"255 200 0 255"
					"image_armedcolor"	"160 125 0 255"
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"wide"			"f0"
						"tall"			"f0"
						"visible"		"1"
						"enabled"		"1"
						"scaleImage"	"1"
						"image"			"replay/thumbnails/menu/glyph/gbanana"
						"proportionaltoparent"	"1"
					}	
				}
			}
		}
	}
}