"_customizations/hud_customization_quick_settings.res"
{
	"SafeMode"
	{
		"CustomizationPanel"
		{
			"CustomizationPanelQuick"
			{
				"ControlName"			"CScrollableList"
				"fieldName"				"CustomizationPanelQuick"
				"wide"					"f0"
				"tall"					"f0"
				"visible"				"0"
				"enabled"				"1"
				"proportionaltoparent"	"1"

				"Scrollbar"
				{
					"xpos"					"rs1+1"
					"wide"					"6"
					"tall"					"f0"
					"zpos"					"1000"
					"proportionaltoparent"	"1"

					"Slider"
					{
						"paintBackgroundType"	"0"
						"fgcolor_override"		"TanLight"
					}

					"nobuttons"				"1"
				}

				"TitleBacker"
				{
					"ControlName"				"Panel"
					"fieldName"					"TitleBacker"
					"wide"						"f0"
					"tall"						"35"
					"visible"					"1"
					"paintBackground"			"1"
					"bgcolor_override"			"GreenSolid"
					"proportionaltoparent"		"1"
				}
				"QuickTitle"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"QuickTitle"
					"xpos"						"-15"
					"ypos"						"2"
					"wide"						"0"
					"tall"						"35"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"#CenHud_Custom_Cat_Quick"
					"font"						"HudFontMediumSmallBold"
					"auto_wide_tocontents"		"1"
					"proportionaltoparent"		"1"

					"pin_to_sibling"		"TitleBacker"
					"pin_to_sibling_corner"	"PIN_CENTER_LEFT"
					"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
				}

				"QuickInfo"
				{
					"ControlName"	"CExImageButton"
					"fieldName"		"QuickInfo"
					"xpos"			"-15"
					"ypos"			"2"
					"zpos"			"7"
					"wide"			"18"
					"tall"			"18"
					"visible"		"1"
					"enabled"		"1"
					"labelText"		""
					"command"		"url https://codeberg.org/RoseyLemonz/center-hud/wiki/Quick-Settings"
					"paintBackground"	"0"
					"proportionaltoparent"		"1"

					"pin_to_sibling"	"TitleBacker"
					"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
					"pin_corner_to_sibling"	"PIN_CENTER_RIGHT"

					"image_drawcolor"	"255 255 255 255"
					"image_armedcolor"	"200 200 200 255"
			
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"zpos"			"1"
						"wide"			"f0"
						"tall"			"f0"
						"visible"		"1"
						"enabled"		"1"
						"image"			"info"
						"scaleImage"	"1"
						"proportionaltoparent"	"1"
					}
				}

				"Options"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"Options"
					"xpos"						"cs-0.5"
					"ypos"						"42"	
					"zpos"						"20"
					"wide"						"f15"
					"tall"						"185"
					"visible"					"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					
					"ChatToggle"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"ChatToggle"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"125"
						"tall"						"22"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle hud_saytext_time 0 12"
							"actionsignallevel"			""
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"25"
							"tall"						"o1"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"hud_saytext_time"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"25"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_ShowChat"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"NetgraphToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"NetgraphToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"125"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"ChatToggle"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle net_graph 0 1"
							"actionsignallevel"			""
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"25"
							"tall"						"o1"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"net_graph"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"25"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_ShowNet"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"ShowposToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"ShowposToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"125"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"NetgraphToggle"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_showpos 0 1"
							"actionsignallevel"			""
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"25"
							"tall"						"o1"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_showpos"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"25"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_ShowPos"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"ShowFPSToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"ShowFPSToggle"
						"xpos"							"0"
						"ypos"							"3"
						"zpos"							"20"
						"wide"							"125"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"ChatToggle"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_showfps 0 1"
							"actionsignallevel"			""
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"25"
							"tall"						"o1"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_showfps"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"25"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_ShowFPS"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"MinmodeToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"MinmodeToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"125"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"ShowFPSToggle"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"


						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_hud_minmode 0 1"
							"actionsignallevel"			""
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"25"
							"tall"						"o1"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_hud_minmode"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"25"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_UseMin"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"MatchStatusToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"MatchStatusToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"125"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"MinmodeToggle"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle tf_use_match_hud 0 1"
							"actionsignallevel"			""
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"25"
							"tall"						"o1"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"tf_use_match_hud"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"25"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_ShowMS"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"CharModelToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"CharModelToggle"
						"xpos"							"0"
						"ypos"							"3"
						"zpos"							"20"
						"wide"							"125"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"ShowFPSToggle"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_hud_playerclass_use_playermodel 0 1"
							"actionsignallevel"			""
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"25"
							"tall"						"o1"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_hud_playerclass_use_playermodel"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"25"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_Use3D"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}
				
					"ContractsToggle"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"ContractsToggle"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"140"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"CharModelToggle"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"ButtonToggle"
						{
							"ControlName"				"CExButton"
							"fieldName"					"ButtonToggle"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle tf_contract_progress_show 0 1"
							"actionsignallevel"			""
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"

							"defaultBgColor_override"	"Blank"
							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"
						}
						"CheckboxImage"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"CheckboxImage"
							"xpos"						"-2"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"25"
							"tall"						"o1"
							"labelText"					""
							"textAlignment"				"west"
							"smallcheckimage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"tf_contract_progress_show"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
						"OptionLabel"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"OptionLabel"
							"xpos"						"25"
							"zpos"						"1"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"#CenHud_Custom_ShowCon"
							"textAlignment"				"west"
							"fgcolor"					"White"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
						}
					}

					"StreamerTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"StreamerTitle"
						"xpos"						"-4"
						"ypos"						"4"
						"zpos"						"10"
						"wide"						"0"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_StreamTitle"
						"font"						"HudFontSmallestBold"
						"auto_wide_tocontents"		"1"
						"use_proportional_insets"	"1"
						"proportionaltoparent"		"1"

						"pin_to_sibling"	"CharModelToggle"
						"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
					}

					"StreamerMessage"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"StreamerMessage"
						"xpos"							"0"
						"ypos"							"2"
						"zpos"							"1"
						"wide"							"f10"
						"tall"							"0"
						"visible"						"1"
						"enabled"						"1"
						"wrap"							"1"
						"font"							"HudFontSmallest"
						"labeltext"						"#CenHud_Custom_StreamMessage"
						"textAlignment"					"north-west"
						"fgcolor"						"Gray"
						"auto_tall_tocontents"			"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"StreamerTitle"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}

					// TODO: Implement

					"StreamerOn"
					{
						"ControlName"					"CExButton"
						"fieldName"						"StreamerOn"
						"xpos"							"0"
						"ypos"							"6"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Enabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				""
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"StreamerMessage"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"StreamerOff"
					{
						"ControlName"					"CExButton"
						"fieldName"						"StreamerOff"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"25"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Disabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"25"
						"command"						""
						"actionsignallevel"				""
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"StreamerOn"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"
					}
					"StreamerWarning"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"StreamerWarning"
						"ypos"							"6"
						"zpos"							"1"
						"tall"							"0"
						"wide"							"f10"
						"visible"						"1"
						"enabled"						"1"
						"labeltext"						"#CenHud_Custom_StreamWarning"
						"font"							"HudFontSmallest"
						"textAlignment"					"north-west"
						"fgcolor"						"TeamRed"
						"wrap"							"1"
						"auto_tall_tocontents"			"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"StreamerOn"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
				}
			}
		}
	}
}