"_customizations/hud_customization_healthammo.res"
{
	"SafeMode"
	{
		"CustomizationPanel"
		{
			"CustomizationPanelHealthAmmo"
			{
				"ControlName"			"CScrollableList"
				"fieldName"				"CustomizationPanelHealthAmmo"
				"wide"					"f0"
				"tall"					"f0"
				"visible"				"0"
				"enabled"				"1"
				"proportionaltoparent"	"1"

				"Scrollbar"
				{
					"xpos"					"rs1+1"
					"wide"					"6"
					"tall"					"f0"
					"zpos"					"1000"
					"proportionaltoparent"	"1"

					"Slider"
					{
						"paintBackgroundType"	"0"
						"fgcolor_override"		"Gray"
					}

					"nobuttons"				"1"
				}

				"HealthAmmoTitle"
				{
					"ControlName"				"CExLabel"
					"fieldName"					"HealthAmmoTitle"
					"xpos"						"15"
					"ypos"						"8"
					"wide"						"f30"
					"tall"						"25"
					"visible"					"1"
					"enabled"					"1"
					"labelText"					"Health And Ammo"
					"font"						"HudFontMediumBold"
					"textAlignment"				"west"
					"fgcolor"					"White"
					"proportionaltoparent"		"1"
				}
				"TitleSeparator"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"TitleSeparator"
					"xpos"						"10"
					"ypos"						"35"
					"zpos"						"0"
					"wide"						"f20"
					"tall"						"2"
					"visible"					"1"
					"enabled"					"1"
					"paintBackgroundtype"		"3"
					"bgcolor_override"			"TanDark"
					"proportionaltoparent"		"1"
				}
				"Options"
				{
					"ControlName"				"EditablePanel"
					"fieldName"					"Options"
					"xpos"						"cs-0.5"
					"ypos"						"40"	
					"zpos"						"20"
					"wide"						"f20"
					"tall"						"235"
					"visible"					"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"

					"HealthTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"HealthTitle"
						"xpos"						"cs-0.5"
						"ypos"						"4"
						"wide"						"f20"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Cat_Health"
						"font"						"HudFontSmallBold"
						"textAlignment"				"west"
						"fgcolor"					"White"
						"proportionaltoparent"		"1"
					}
					"HealthSeperator"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"HealthSeperator"
						"xpos"						"0"
						"ypos"						"4"
						"wide"						"f10"
						"tall"						"2"
						"visible"					"1"
						"enabled"					"1"
						"paintBackgroundtype"		"3"
						"bgcolor_override"			"TanDark"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"HealthTitle"
						"pin_to_sibling_corner"		"PIN_CENTER_BOTTOM"
						"pin_corner_to_sibling"		"PIN_CENTER_BOTTOM"
					}

					"HealthOn"
					{
						"ControlName"					"CExButton"
						"fieldName"						"HealthOn"
						"xpos"							"-5"
						"ypos"							"6"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"20"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Enabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"20"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"HealthSeperator"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"HealthOff"
					{
						"ControlName"					"CExButton"
						"fieldName"						"HealthOff"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"20"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"labelText"						"#CenHud_Custom_Gen_Disabled"
						"textAlignment"					"center"
						"font"							"HudFontSmallBold"
						"textinsetx"					"20"
						"command"						""
						"actionsignallevel"				"5"
						"auto_wide_tocontents"			"1"
						"proportionaltoparent"			"1"
						"use_proportional_insets"		"1"
						"sound_depressed"		"UI/buttonclick.wav"
						"sound_released"		"UI/buttonclickrelease.wav"

						"pin_to_sibling"				"HealthOn"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"
					}

					"HealthValueSubtitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"HealthValueSubtitle"
						"xpos"						"0"
						"ypos"						"6"
						"wide"						"f25"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Gen_Value"
						"font"						"HudFontSmallestBold"
						"textAlignment"				"west"
						"fgcolor"					"Gray"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"HealthOn"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"		
					}
					"HealthValue"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"HealthValue"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"110"
						"tall"						"o0.8"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"HealthValueSubtitle"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_ammo"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"
							"paintBackgroundType"		"2"
							"roundedcorners"			"11"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel_wide"
								"drawcolor"		"160 160 160 255"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"PlayerHealthValue"
							{
								"ControlName"	"CExLabel"
								"fieldName"		"PlayerHealthValue"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.49"
								"zpos"			"4"
								"wide"			"51"
								"tall"			"o0.5"
								"visible"		"1"
								"enabled"		"1"
								"labelText"		"#CenHud_Custom_Gen_NumValue"
								"textAlignment"	"center"	
								"font"			"HudClassHealth"
								"fgcolor"		"TanDark"
								"proportionaltoparent"	"1"
							}
							"HealthImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"HealthImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"3"
								"wide"			"51"
								"tall"			"o1"
								"visible"		"1"
								"image"			"../hud/health_color"
								"scaleImage"	"1"
								"proportionaltoparent"	"1"
							}		
							"HealthImageBG"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"HealthImageBG"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"2"
								"wide"			"55"
								"tall"			"o1"
								"visible"		"1"
								"image"			"../hud/health_bg"
								"scaleImage"	"1"
								"proportionaltoparent"	"1"
							}
						}
					}		
					"HealthNoValue"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"HealthNoValue"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"110"
						"tall"						"o0.8"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"HealthValue"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_health"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel_wide"
								"drawcolor"		"160 160 160 255"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"HealthImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"HealthImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"3"
								"wide"			"51"
								"tall"			"o1"
								"visible"		"1"
								"image"			"../hud/health_color"
								"scaleImage"	"1"
								"proportionaltoparent"	"1"
							}		
							"HealthImageBG"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"HealthImageBG"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"2"
								"wide"			"55"
								"tall"			"o1"
								"visible"		"1"
								"image"			"../hud/health_bg"
								"scaleImage"	"1"
								"proportionaltoparent"	"1"
							}
						}
					}

					"HealSubTitle"
					{
						"ControlName"				"CExLabel"
						"fieldName"					"HealSubTitle"
						"xpos"						"0"
						"ypos"						"4"
						"wide"						"f25"
						"tall"						"15"
						"visible"					"1"
						"enabled"					"1"
						"labelText"					"#CenHud_Custom_Gen_Health_HealFont"
						"font"						"HudFontSmallestBold"
						"textAlignment"				"west"
						"fgcolor"					"Gray"
						"proportionaltoparent"		"1"

						"pin_to_sibling"			"HealthValue"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"
					}
					"HealSecondary"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"HealSecondary"
						"xpos"						"0"
						"ypos"						"2"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"HealSubTitle"
						"pin_to_sibling_corner"		"PIN_BOTTOMLEFT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_health"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel"
								"drawcolor"		"160 160 160 255"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"HealthValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"HealthValue"
								"xpos"				"cs-0.5"
								"ypos"				"cs-0.5"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f0"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_PosValue"
								"textAlignment"		"center"
								"font"				"HudFontMediumOutline"
								"fgcolor"			"0 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
					"HealBold"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"HealBold"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"HealSecondary"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_ammo"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"
							"paintBackgroundType"		"2"
							"roundedcorners"			"11"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel"
								"drawcolor"		"160 160 160 255"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"HealthValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"HealthValue"
								"xpos"				"cs-0.5"
								"ypos"				"cs-0.5"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f0"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_PosValue"
								"textAlignment"		"center"
								"font"				"HudFontMediumBoldOutline"
								"fgcolor"			"0 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
					"HealSecondaryNoOutline"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"HealSecondaryNoOutline"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"HealBold"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_health"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel"
								"drawcolor"		"160 160 160 255"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"HealthValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"HealthValue"
								"xpos"				"cs-0.5"
								"ypos"				"cs-0.5"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f0"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_PosValue"
								"textAlignment"		"center"
								"font"				"HudFontMedium"
								"fgcolor"			"0 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
					"HealBoldNoOutline"
					{
						"ControlName"				"EditablePanel"
						"fieldName"					"HealBoldNoOutline"
						"xpos"						"5"
						"ypos"						"0"
						"wide"						"70"
						"tall"						"70"
						"visible"					"1"
						"enabled"					"1"
						"proportionaltoparent"		"1"
						"pin_to_sibling"			"HealSecondaryNoOutline"
						"pin_to_sibling_corner"		"PIN_TOPRIGHT"

						"Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Button"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine cenhud_ldd_pos_ammo"
							"actionsignallevel"			"6"
							"paintBackground"			"1"
							"paintBorder"				"0"
							"proportionaltoparent"		"1"
							"sound_depressed"		"UI/buttonclick.wav"
							"sound_released"		"UI/buttonclickrelease.wav"
						}

						"PreviewPanel"
						{
							"ControlName"				"EditablePanel"
							"fieldName"					"PreviewPanel"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f15"
							"tall"						"f15"
							"proportionaltoparent"		"1"
							"mouseinputenabled" 		"0"
							"paintBackgroundType"		"2"
							"roundedcorners"			"11"

							"MapBGImage"
							{
								"ControlName"	"ImagePanel"
								"fieldName"		"MapBGImage"
								"xpos"			"cs-0.5"
								"ypos"			"cs-0.5"
								"zpos"			"1"
								"wide"			"f0"
								"tall"			"f0"
								"visible"		"1"
								"image"			"replay/thumbnails/menu/customization/previewpanel"
								"drawcolor"		"160 160 160 255"
								"scaleImage"	"1"	
								"proportionaltoparent"	"1"			
							}

							"HealthValue"
							{
								"ControlName"		"CExLabel"
								"fieldName"			"HealthValue"
								"xpos"				"cs-0.5"
								"ypos"				"cs-0.5"
								"zpos"				"3"
								"wide"				"f0"
								"tall"				"f0"
								"visible"			"1"
								"enabled"			"1"
								"labelText"			"#CenHud_Custom_Gen_PosValue"
								"textAlignment"		"center"
								"font"				"HudFontMediumBold"
								"fgcolor"			"0 255 0 255"
								"proportionaltoparent"	"1"		
							}
						}
					}
				}
			}
		}
	}
}