#base "customfontfiles.res"
#base "../_addons/_enabled/refont/altclientscheme.res"
#base "../_scheme/clientscheme-baseset.res"
#base "../_scheme/clientscheme-colors.res"
#base "../_scheme/clientscheme-fonts.res"
#base "../_scheme/clientscheme-borders.res"
