#base "customfontfiles.res"
#base "../cfg/centerhud/hud_clientscheme.txt"
#base "../_scheme/clientscheme-baseset.res"
#base "../_scheme/clientscheme-colors.res"
#base "../_scheme/clientscheme-fonts.res"
#base "../_scheme/clientscheme-borders.res"
