#base "../../../cfg/hud_sourcescheme.txt"
#base "../_scheme/sourcescheme-baseset.res"
#base "../_scheme/sourcescheme-colors.res"
#base "../_scheme/sourcescheme-fonts.res"
#base "SourceSchemeBase.res"
