"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Home.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Customization_Home_Panel"
			{
				"ControlName"			"EditablePanel"
				"fieldName"				"HUD_Customization_Home_Panel"
				"xpos"					"0"
				"ypos"					"0"
				"zpos"					"0"
				"wide"					"f0"
				"tall"					"f0"
				"visible"				"1"
				"enabled"				"1"
				"paintBackground"		"0"
				"proportionaltoparent"	"1"

				"Title"
				{
					"ControlName"			"CExLabel"
					"fieldName"				"Title"
					"xpos"					"15"
					"ypos"					"8"
					"zpos"					"0"
					"wide"					"f30"
					"tall"					"25"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"		"1"
					"use_proportional_insets"	"1"
					"allcaps"					"1"
					"labelText"				"#CenHud_Desc_Welcome"
					"font"					"HudFontMediumbold"
					"textAlignment"			"west"
					"fgcolor"				"White"
				}
				"Description"
				{
					"ControlName"			"CExLabel"
					"fieldName"				"Description"
					"xpos"					"16"
					"ypos"					"32"
					"zpos"					"0"
					"wide"					"f32"
					"tall"					"15"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"use_proportional_insets"	"1"
					"labelText"				"#CenHud_Desc_Category"
					"font"					"HudFontSmall"
					"textAlignment"			"west"
					"fgcolor"				"Gray"
				}
				"Separator_1"
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"Separator_1"
					"xpos"					"10"
					"ypos"					"50"
					"zpos"					"0"
					"wide"					"f20"
					"tall"					"2"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"paintBackground"			"1"
					"paintBackgroundtype"	"3"
					"bgcolor_override"		"TanDark"
				}
				"Warning_Icon"
				{
					"ControlName"			"ImagePanel"
					"fieldName"				"Warning_Icon"
					"xpos"					"16"
					"ypos"					"65"
					"zpos"					"0"
					"wide"					"20"
					"tall"					"o1"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"drawcolor"					"Red"
					"scaleImage"				"1"
					"image"						"replay/thumbnails/menu/glyph/refresh"
				}
				"Warning_1"
				{
					"ControlName"			"CExLabel"
					"fieldName"				"Warning_1"
					"xpos"					"45"
					"ypos"					"52"
					"zpos"					"0"
					"wide"					"f55"
					"tall"					"50"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"use_proportional_insets"	"1"
					"Wrap"					"1"
					"labelText"				"#CenHud_Desc_Warn_Restart"
					"font"					"HudFontSmallerOutline"
					"fgcolor"				"RedSolid"
					"textAlignment"			"west"
					"fgcolor"				"White"
				}
				"Separator_2"
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"Separator_2"
					"xpos"					"10"
					"ypos"					"102"
					"zpos"					"0"
					"wide"					"f20"
					"tall"					"2"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"paintBackground"			"1"
					"paintBackgroundtype"	"3"
					"bgcolor_override"		"TanDark"
				}
				"Support_Icon"
				{
					"ControlName"			"ImagePanel"
					"fieldName"				"Support_Icon"
					"xpos"					"16"
					"ypos"					"126"
					"zpos"					"0"
					"wide"					"20"
					"tall"					"o1"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"drawcolor"					"QuestGold"
					"scaleImage"				"1"
					"image"						"replay/thumbnails/menu/glyph/repo"
				}
				"Support_1"
				{
					"ControlName"			"CExLabel"
					"fieldName"				"Support_1"
					"xpos"					"45"
					"ypos"					"107"
					"zpos"					"0"
					"wide"					"f55"
					"tall"					"65"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"use_proportional_insets"	"1"
					"Wrap"					"1"
					"labelText"				"#CenHud_Desc_Contribute"
					"font"					"HudFontSmallerOutline"
					"textAlignment"			"west"
					"fgcolor"				"White"
				}
				"Separator_3"
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"Separator_3"
					"xpos"					"10"
					"ypos"					"178"
					"zpos"					"0"
					"wide"					"f20"
					"tall"					"2"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"paintBackground"			"1"
					"paintBackgroundtype"		"3"
					"bgcolor_override"		"TanDark"
				}
				"Links_Desc"
				{
					"ControlName"			"CExLabel"
					"fieldName"				"Links_Desc"
					"xpos"					"15"
					"ypos"					"182"
					"zpos"					"0"
					"wide"					"0"
					"tall"					"18"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"allcaps"					"1"
					"labelText"				"#CenHud_Desc_CallToAction"
					"font"					"HudFontSmallestbold"
					"textAlignment"			"west"
					"fgcolor"				"Gray"
					"auto_wide_tocontents"	"1"
				}
				"GitHub_Link"
				{
					"ControlName"			"CExImageButton"
					"fieldName"				"GitHub_Link"
					"xpos"					"3"
					"ypos"					"0"
					"zpos"					"20"
					"wide"					"18"
					"tall"					"o1"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"labelText"					""
					"textAlignment"			"center"
					"command"				"url https://github.com/RoseyLemonz/center-hud"
					"paintBackground"		"0"

					"pin_to_sibling"			"Links_Desc"
					"pin_corner_to_sibling"		"PIN_TOPLEFT"
					"pin_to_sibling_corner"		"PIN_TOPRIGHT"

					"image_drawcolor"	"255 255 255 255"
					"image_armedcolor"	"192 192 192 255"
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"wide"			"f0"
						"tall"			"o1"
						"visible"		"1"
						"enabled"		"1"
						"scaleImage"	"1"
						"image"			"replay/thumbnails/menu/glyph/ghub"
						"proportionaltoparent"	"1"
					}			
				}
				"ComfigHUDs_Link"
				{
					"ControlName"			"CExImageButton"
					"fieldName"				"ComfigHUDs_Link"
					"xpos"					"3"
					"ypos"					"0"
					"zpos"					"20"
					"wide"					"18"
					"tall"					"o1"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"labelText"					""
					"textAlignment"			"center"
					"command"				"url https://comfig.app/huds/page/center-hud/"
					"paintBackground"		"0"

					"pin_to_sibling"			"GitHub_Link"
					"pin_corner_to_sibling"		"PIN_TOPLEFT"
					"pin_to_sibling_corner"		"PIN_TOPRIGHT"

					"image_drawcolor"	"0 150 135 255"
					"image_armedcolor"	"0 100 90 255"
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"wide"			"f2"
						"tall"			"o1"
						"visible"		"1"
						"enabled"		"1"
						"scaleImage"	"1"
						"image"			"replay/thumbnails/menu/glyph/coms"
						"proportionaltoparent"	"1"
					}			
				}
				"TF2HUDs_Link"
				{
					"ControlName"			"CExImageButton"
					"fieldName"				"TF2HUDs_Link"
					"xpos"					"3"
					"ypos"					"0"
					"zpos"					"20"
					"wide"					"18"
					"tall"					"o1"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"labelText"					""
					"textAlignment"			"center"
					"command"				"url https://tf2huds.dev/hud/Center-Hud"
					"paintBackground"		"0"

					"pin_to_sibling"			"ComfigHUDs_Link"
					"pin_corner_to_sibling"		"PIN_TOPLEFT"
					"pin_to_sibling_corner"		"PIN_TOPRIGHT"

					"image_drawcolor"	"255 85 0 255"
					"image_armedcolor"	"145 50 0 255"
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"wide"			"f4"
						"tall"			"o1"
						"visible"		"1"
						"enabled"		"1"
						"scaleImage"	"1"
						"image"			"glyph_multiplayer"
						"proportionaltoparent"	"1"
					}			
				}
				"GameBanana_Link"
				{
					"ControlName"			"CExImageButton"
					"fieldName"				"GameBanana_Link"
					"xpos"					"3"
					"ypos"					"0"
					"zpos"					"20"
					"wide"					"18"
					"tall"					"o1"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"labelText"					""
					"textAlignment"			"center"
					"command"				"url https://gamebanana.com/mods/485626"
					"paintBackground"		"0"

					"pin_to_sibling"			"TF2HUDs_Link"
					"pin_corner_to_sibling"		"PIN_TOPLEFT"
					"pin_to_sibling_corner"		"PIN_TOPRIGHT"

					"image_drawcolor"	"255 200 0 255"
					"image_armedcolor"	"160 125 0 255"
					"SubImage"
					{
						"ControlName"	"ImagePanel"
						"fieldName"		"SubImage"
						"xpos"			"cs-0.5"
						"ypos"			"cs-0.5"
						"wide"			"f2"
						"tall"			"o1"
						"visible"		"1"
						"enabled"		"1"
						"scaleImage"	"1"
						"image"			"replay/thumbnails/menu/glyph/gbanana"
						"proportionaltoparent"	"1"
					}	
				}
			}
		}
	}
}