"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Damage.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Damage_Selection"
			{
				"ControlName"							"CScrollableList"
				"fieldName"								"HUD_Damage_Selection"
				"xpos"									"cs-0.5"
				"ypos"									"cs-0.5"
				"zpos"									"0"
				"wide"									"f0"
				"tall"									"f0"
				"visible"								"0"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"paintBackground"						"0"
				"paintBackgroundType"					"0"
				"bgcolor_override"						"Black"

				"Scrollbar"
				{
					"xpos"								"rs1+1"
					"ypos"								"0"
					"wide"								"6"
					"tall"								"f0"
					"zpos"								"1000"
					"proportionaltoparent"				"1"

					"Slider"
					{
						"PaintBackgroundType"			"0"
						"FGColor_Override"				"Gray"
					}

					"nobuttons"							"1"
				}
				"Title_Icon"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title_Icon"
					"xpos"								"4"
					"ypos"								"2"
					"zpos"								"0"
					"wide"								"20"
					"tall"								"25"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"labelText"							"l"
					"font"								"Symbols24"
					"textAlignment"						"center"
					"fgcolor"							"Gray"
				}
				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"30"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f25"
					"tall"								"27"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"labelText"							"DAMAGE"
					"font"								"HudFontMediumbold"
					"textAlignment"						"west"
					"fgcolor"							"Gray"
				}
				"Separator_1"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Separator_1"
					"xpos"								"3"
					"ypos"								"28"
					"zpos"								"0"
					"wide"								"f40"
					"tall"								"2"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintBackground"					"1"
					"paintBackgroundtype"				"3"
					"bgcolor_override"					"Background_Bright"
				}
// FLOATING DAMAGE STYLE -----------------------------------------------------------------------------------
				"Floating_Damage_Style"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Floating_Damage_Style"
					"xpos"								"0"
					"ypos"								"36"
					"zpos"								"20"
					"wide"								"f7"
					"tall"								"100"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Damage_Title"
						"xpos"							"4"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f35"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"allcaps"						"1"
						"labelText"						"Floating Damage Style And Size"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"fgcolor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Separator"
						"xpos"							"2"
						"ypos"							"15"
						"zpos"							"0"
						"wide"							"f40"
						"tall"							"1"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"bgcolor_override"				"Background_Bright"
					}
// DAMAGE SMALL -------------------------------------------------------------------------------------------
					"Damage_Small"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Small"
						"xpos"							"-2"
						"ypos"							"5"
						"zpos"							"1"
						"wide"							"68"
						"tall"							"68"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Separator"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-7"
							"zpos"						"0"
							"wide"						"70"
							"tall"						"70"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/damage_small"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Small"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_small"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// DAMAGE SMALL MINUSLESS -------------------------------------------------------------------------------------------
					"Damage_Small_Minusless"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Small_Minusless"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"68"
						"tall"							"68"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Damage_Small"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-7"
							"zpos"						"0"
							"wide"						"70"
							"tall"						"70"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/damage_small_minusless"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Small Minusless"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_small_minusless"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// DAMAGE MEDIUM -------------------------------------------------------------------------------------------
					"Damage_Medium"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Medium"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"68"
						"tall"							"68"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Damage_Small_Minusless"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-7"
							"zpos"						"0"
							"wide"						"70"
							"tall"						"70"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/damage_medium"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Medium"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_medium"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// DAMAGE MEDIUM MINUSLESS -------------------------------------------------------------------------------------------
					"Damage_Medium_Minusless"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Medium_Minusless"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"68"
						"tall"							"68"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Damage_Medium"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-7"
							"zpos"						"0"
							"wide"						"70"
							"tall"						"70"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/damage_medium_minusless"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Medium Minusless"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_medium_minusless"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// DAMAGE BIG -------------------------------------------------------------------------------------------
					"Damage_Big"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Big"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"68"
						"tall"							"68"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Damage_Medium_Minusless"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-7"
							"zpos"						"0"
							"wide"						"70"
							"tall"						"70"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/damage_big"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Big"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_big"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
// DAMAGE BIG MINUSLESS -------------------------------------------------------------------------------------------
					"Damage_Big_Minusless"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Big_Minusless"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"68"
						"tall"							"68"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Damage_Big"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-7"
							"zpos"						"0"
							"wide"						"70"
							"tall"						"70"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/damage_big_minusless"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Big Minusless"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_big_minusless"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
// FLOATING DAMAGE TRANSPARENCY ----------------------------------------------------------------------------
				"Floating_Damage_Transparency"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Floating_Damage_Transparency"
					"xpos"								"0"
					"ypos"								"135"
					"zpos"								"20"
					"wide"								"220"
					"tall"								"80"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Damage_Title"
						"xpos"							"4"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f35"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"allcaps"						"1"
						"labelText"						"Floating Damage Transparency"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"fgcolor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Separator"
						"xpos"							"2"
						"ypos"							"15"
						"zpos"							"0"
						"wide"							"f15"
						"tall"							"1"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"bgcolor_override"				"Background_Bright"
					}
					"Damage_Solid"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Solid"
						"xpos"							"-2"
						"ypos"							"5"
						"zpos"							"1"
						"wide"							"68"
						"tall"							"50"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Separator"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Damage_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Example"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"Showcase_Damage_Big"
							"labelText"					"-135"
							"textAlignment"				"center"
							"fgcolor"					"White"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Solid"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_trans_clear"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Damage_Transparent"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Transparent"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"68"
						"tall"							"50"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Damage_Solid"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Damage_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Example"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"Showcase_Damage_Big"
							"labelText"					"-135"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"Alpha"						"150"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Transparent"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_transparent"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
// DAMAGE CVARS ----------------------------------------------------------------------------
				"Damage_Cvars"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Damage_Cvars"
					"xpos"								"230"
					"ypos"								"135"
					"zpos"								"20"
					"wide"								"200"
					"tall"								"80"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Damage_Title"
						"xpos"							"4"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f35"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"allcaps"						"1"
						"labelText"						"Damage Settings"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"fgcolor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Separator"
						"xpos"							"2"
						"ypos"							"15"
						"zpos"							"0"
						"wide"							"f15"
						"tall"							"1"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"bgcolor_override"				"Background_Bright"
					}
					"Damage_Batching"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Batching"
						"xpos"							"0"
						"ypos"							"2"
						"zpos"							"1"
						"wide"							"150"
						"tall"							"16"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"0"

						"pin_to_sibling"				"Separator"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Toggle_Button"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"20"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"actionsignallevel"			"6"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle hud_combattext_batching 0 1"
							"sound_depressed"			"UI/buttonclick.wav"
							"paintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"DefaultBGColor_Override"	"Blank"
							"ArmedBGColor_Override"		"Button_Hover"
							"DepressedBGColor_Override"	"Button_Hover"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"Setting_Checkbox"
							"xpos"						"-2"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"19"
							"tall"						"f0"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"SmallCheckImage"			"1"
							"button_activation_type"	"1"
							"cvar_name"					"hud_combattext_batching"
							"mouseinputenabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Setting_Label"
							"xpos"						"19"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"allcaps"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"HudFontSmallest"
							"labelText"					"Allow Damage Batching"
							"textAlignment"				"west"
							"Wrap"						"0"
							"fgcolor"					"White"
						}
					}
					"Batching_Window_Label"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Batching_Window_Label"
						"xpos"							"-2"
						"ypos"							"20"
						"zpos"							"1"
						"wide"							"160"
						"tall"							"12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"allcaps"						"1"
						"font"							"HudFontSmallest"
						"labelText"						"Damage Batching Window: "
						"textAlignment"					"west"
						"fgcolor"						"Gray"

						"pin_to_sibling"				"Separator"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"Batching_Window_Slider"
					{
						"ControlName"					"CCvarSlider"
						"fieldName"						"Batching_Window_Slider"
						"xpos"							"-5"
						"ypos"							"0"
						"zpos"							"2"
						"wide"							"160"
						"tall"							"30"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"minvalue"						"0.1"
						"maxvalue"						"2"
						"cvar_name"						"hud_combattext_batching_window"

						"pin_to_sibling"				"Batching_Window_Label"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
				}
// LAST DAMAGE DONE STYLE -----------------------------------------------------------------------------------
				"Last_Damage_Done_Style"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Last_Damage_Done_Style"
					"xpos"								"0"
					"ypos"								"220"
					"zpos"								"20"
					"wide"								"f7"
					"tall"								"100"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Damage_Title"
						"xpos"							"4"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f35"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"allcaps"						"1"
						"labelText"						"Last Damage Done Style"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"fgcolor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Separator"
						"xpos"							"2"
						"ypos"							"15"
						"zpos"							"0"
						"wide"							"f40"
						"tall"							"1"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"bgcolor_override"				"Background_Bright"
					}
					"Last_Damage_Disabled"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_Disabled"
						"xpos"							"-2"
						"ypos"							"5"
						"zpos"							"1"
						"wide"							"70"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Separator"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-5"
							"zpos"						"0"
							"wide"						"56"
							"tall"						"56"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/last_damage_health"
						}
						"Style_Disabled"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Disabled"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-6"
							"zpos"						"3"
							"wide"						"68"
							"tall"						"42"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/general/disabled_cross"
							"ScaleImage"				"1"
							"Drawcolor"					"Red"
							"Alpha"						"200"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Disabled"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_last_damage_clear"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Last_Damage_Health"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_Health"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"70"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Last_Damage_Disabled"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-5"
							"zpos"						"0"
							"wide"						"56"
							"tall"						"56"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/last_damage_health"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Above Health"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_last_damage_health"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Last_Damage_Cross"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_Cross"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"70"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Last_Damage_Health"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-7"
							"zpos"						"0"
							"wide"						"56"
							"tall"						"56"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/last_damage_cross"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Cross Style"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_last_damage_cross"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Last_Damage_Ammo"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_Ammo"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"70"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Last_Damage_Cross"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-5"
							"zpos"						"0"
							"wide"						"56"
							"tall"						"56"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/last_damage_ammo"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Above Ammo"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_last_damage_ammo"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Last_Damage_Centered"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_Centered"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"70"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Last_Damage_Ammo"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-5"
							"zpos"						"0"
							"wide"						"50"
							"tall"						"50"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/last_damage_center"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Centered"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_last_damage_center"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
// DAMAGE INDICATORS -----------------------------------------------------------------------------------
				"Damage_Indicators"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Damage_Indicators"
					"xpos"								"0"
					"ypos"								"320"
					"zpos"								"20"
					"wide"								"f7"
					"tall"								"100"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Damage_Title"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Damage_Title"
						"xpos"							"4"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f35"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"allcaps"						"1"
						"labelText"						"Damage Idicator"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"fgcolor"						"Gray"
					}
					"Separator"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Separator"
						"xpos"							"2"
						"ypos"							"15"
						"zpos"							"0"
						"wide"							"f40"
						"tall"							"1"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"bgcolor_override"				"Background_Bright"
					}
					"Indicator_Disabled"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Indicator_Disabled"
						"xpos"							"-2"
						"ypos"							"5"
						"zpos"							"1"
						"wide"							"70"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Separator"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-7"
							"zpos"						"0"
							"wide"						"56"
							"tall"						"56"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/damage_indicator_big"
						}
						"Style_Disabled"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Disabled"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-6"
							"zpos"						"3"
							"wide"						"68"
							"tall"						"42"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/general/disabled_cross"
							"ScaleImage"				"1"
							"Drawcolor"					"Red"
							"Alpha"						"200"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Disabled"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_indicator_off"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Indicator_Big"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Indicator_Big"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"70"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Indicator_Disabled"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-7"
							"zpos"						"0"
							"wide"						"56"
							"tall"						"56"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/damage_indicator_big"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Big"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_indicator_big"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					"Indicator_Small"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Indicator_Small"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"70"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"bgcolor_override"				"104 101 100 255"

						"pin_to_sibling"				"Indicator_Big"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Style_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Style_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-5"
							"zpos"						"0"
							"wide"						"56"
							"tall"						"56"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"ScaleImage"				"1"
							"proportionaltoparent"		"1"
							"Image"						"replay/thumbnails/customizations/damage/damage_indicator_small"
						}
						"Style_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Style_Label"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"12"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"allcaps"					"1"
							"font"						"FontStorePrice"
							"labelText"					"Small"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"Background_Darkest"
						}
						"Style_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Style_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_damage_indicator_clear"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
				}
			}
		}
	}
}