"resource/ui/customizations/#customization_menu/hud_customization_quick_settings.res"
{
	"SafeMode"
	{
		"Customizations_Panel"
		{
			"HUD_Quick_Settings_Selection"
			{
				"ControlName"			"CScrollableList"
				"fieldName"				"HUD_Quick_Settings_Selection"
				"xpos"					"cs-0.5"
				"ypos"					"cs-0.5"
				"zpos"					"0"
				"wide"					"f0"
				"tall"					"f0"
				"visible"				"0"
				"enabled"				"1"
				"proportionaltoparent"	"1"
				"paintBackground"		"0"
				"paintBackgroundType"	"0"
				"bgcolor_override"		"Black"

				"Scrollbar"
				{
					"xpos"				"rs1+1"
					"ypos"				"0"
					"wide"				"6"
					"tall"				"f0"
					"zpos"				"1000"
					"proportionaltoparent"	"1"

					"Slider"
					{
						"PaintBackgroundType"	"0"
						"FGColor_Override"		"Gray"
					}

					"nobuttons"				"1"
				}
				"Title"
				{
					"ControlName"			"CExLabel"
					"fieldName"				"Title"
					"xpos"					"15"
					"ypos"					"8"
					"zpos"					"0"
					"wide"					"f30"
					"tall"					"25"
					"visible"				"1"
					"enabled"				"1"
					"proportionaltoparent"	"1"
					"allcaps"				"1"
					"labelText"				"Template"
					"font"					"HudFontMediumbold"
					"textAlignment"			"west"
					"fgcolor"				"White"
				}
				"Separator_1"
				{
					"ControlName"			"EditablePanel"
					"fieldName"				"Separator_1"
					"xpos"					"10"
					"ypos"					"35"
					"zpos"					"0"
					"wide"					"f20"
					"tall"					"2"
					"visible"				"1"
					"enabled"					"1"
					"proportionaltoparent"		"1"
					"paintBackground"			"1"
					"paintBackgroundtype"	"3"
					"bgcolor_override"		"TanDark"
				}
				"Settings"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Settings"
					"xpos"								"15"
					"ypos"								"40"
					"zpos"								"20"
					"wide"								"f30"
					"tall"								"250"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					
					"Toggle_Chat"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Toggle_Chat"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Toggle_Button"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"20"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"actionsignallevel"			"6"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle hud_saytext_time 0 12"
							"sound_depressed"			"UI/buttonclick.wav"
							"paintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"

							"defaultBgColor_override"	"Blank"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"Setting_Checkbox"
							"xpos"						"-2"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"22"
							"tall"						"22"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"hud_saytext_time"
							"mouseinputenabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Setting_Label"
							"xpos"						"24"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"HudFontSmallest"
							"labelText"					"Show Ingame Chat"
							"textAlignment"				"west"
							"Wrap"						"0"
							"fgcolor"					"White"
						}
					}

					"Toggle_Netgraph"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Toggle_Netgraph"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"Toggle_Chat"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Toggle_Button"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"20"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"actionsignallevel"			"6"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle net_graph 0 1"
							"sound_depressed"			"UI/buttonclick.wav"
							"paintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"

							"defaultBgColor_override"	"Blank"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"Setting_Checkbox"
							"xpos"						"-2"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"22"
							"tall"						"22"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"net_graph"
							"mouseinputenabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Setting_Label"
							"xpos"						"24"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"HudFontSmallest"
							"labelText"					"Show Net-Graph"
							"textAlignment"				"west"
							"Wrap"						"0"
							"fgcolor"					"White"
						}
					}

					"Toggle_ShowPos"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Toggle_ShowPos"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"Toggle_NetGraph"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Toggle_Button"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"20"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"actionsignallevel"			"6"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_showpos 0 1"
							"sound_depressed"			"UI/buttonclick.wav"
							"paintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"

							"defaultBgColor_override"	"Blank"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"Setting_Checkbox"
							"xpos"						"-2"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"22"
							"tall"						"22"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_showpos"
							"mouseinputenabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Setting_Label"
							"xpos"						"24"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"HudFontSmallest"
							"labelText"					"Show Position Graph"
							"textAlignment"				"west"
							"Wrap"						"0"
							"fgcolor"					"White"
						}
					}

					"Toggle_ShowFPS"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Toggle_ShowFPS"
						"xpos"							"0"
						"ypos"							"3"
						"zpos"							"20"
						"wide"							"120"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"Toggle_Chat"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Toggle_Button"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"20"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"actionsignallevel"			"6"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle cl_showfps 0 1"
							"sound_depressed"			"UI/buttonclick.wav"
							"paintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"

							"defaultBgColor_override"	"Blank"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"Setting_Checkbox"
							"xpos"						"-2"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"22"
							"tall"						"22"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"cl_showfps"
							"mouseinputenabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Setting_Label"
							"xpos"						"24"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"HudFontSmallest"
							"labelText"					"Show FPS Counter"
							"textAlignment"				"west"
							"Wrap"						"0"
							"fgcolor"					"White"
						}
					}

					"Toggle_Contracts"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Toggle_Contracts"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"135"
						"tall"							"22"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"Toggle_ShowFPS"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Toggle_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Toggle_Button"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"20"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"actionsignallevel"			"6"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"command"					"engine toggle tf_contract_progress_show 0 1"
							"sound_depressed"			"UI/buttonclick.wav"
							"paintBackground"			"1"
							"PaintBorder"				"0"

							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"

							"defaultBgColor_override"	"Blank"
						}
						"Setting_Checkbox"
						{
							"ControlName"				"CvarToggleCheckButton"
							"fieldName"					"Setting_Checkbox"
							"xpos"						"-2"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"22"
							"tall"						"22"
							"proportionaltoparent"		"1"
							"labelText"					""
							"textAlignment"				"west"
							"SmallCheckImage"			"0"
							"button_activation_type"	"1"
							"cvar_name"					"tf_contract_progress_show"
							"mouseinputenabled"			"0"
						}
						"Setting_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Setting_Label"
							"xpos"						"24"
							"ypos"						"cs-0.5"
							"zpos"						"21"
							"wide"						"f24"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"HudFontSmallest"
							"labelText"					"Show Active Contracts"
							"textAlignment"				"west"
							"Wrap"						"0"
							"fgcolor"					"White"
						}
					}

					"Close_Captions"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Close_Captions"
						"xpos"							"5"
						"ypos"							"55"
						"zpos"							"0"
						"wide"							"f25"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"allcaps"						"1"
						"labelText"						"Close Captions"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"fgcolor"						"White"
					}
					"Separator_2"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Separator_2"
						"xpos"							"3"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f6"
						"tall"							"1"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"bgcolor_override"				"TanDark"
						
						"pin_to_sibling"				"Close_Captions"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"	
					}

					"Captions_ON"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Captions_ON"
						"xpos"							"-2"
						"ypos"							"5"
						"zpos"							"20"
						"wide"							"100"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"Separator_2"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"

						"Element_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Element_Name"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"20"
							"visible"					"1"
							"enabled"					"1"
							"allcaps"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"HudFontSmallestBold"
							"labelText"					"enabled"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintBackground"			"1"
							"PaintBackgroundType"		"2"
							"roundedcorners"			"3"
							"bgcolor_override"			"StoreGreen"
						}
						"Captions_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Captions_Example"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"2"
							"wide"						"f0"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"Wrap"						"1"
							"CenterWrap"				"1"
							"allcaps"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"Scout Hurt Ubercharge Ready Medic Hurt"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"HudBlack"
						}
						"Resolution_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Resolution_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine closecaption 1;cc_subtitles 0;cc_lang english;cc_predisplay_time 0;cc_emit #subtitles0"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"NoBorder"

						}
					}

					"Captions_OFF"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Captions_OFF"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"100"
						"tall"							"60"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"

						"pin_to_sibling"				"Captions_ON"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Element_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Element_Name"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"4"
							"wide"						"f0"
							"tall"						"20"
							"visible"					"1"
							"enabled"					"1"
							"allcaps"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"HudFontSmallestBold"
							"labelText"					"Disabled"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintBackground"			"1"
							"PaintBackgroundType"		"2"
							"roundedcorners"			"3"
							"bgcolor_override"			"StoreGreen"
						}
						"Captions_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Captions_Example"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"2"
							"wide"						"f0"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"Wrap"						"1"
							"CenterWrap"				"1"
							"allcaps"					"1"
							"font"						"HudFontSmallest"
							"labelText"					"-----"
							"textAlignment"				"center"
							"fgcolor"					"Gray"
							"paintBackground"			"1"
							"PaintBackgroundType"		"0"
							"bgcolor_override"			"HudBlack"
						}
						"Resolution_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Resolution_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine closecaption 0; cc_predisplay_time 0"
							"labelText"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintBackground"			"0"
							"PaintBorder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionGray"
						}
					}
					
					"Streamer_Mode"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Streamer_Mode"
						"xpos"							"5"
						"ypos"							"140"
						"zpos"							"0"
						"wide"							"f25"
						"tall"							"15"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"allcaps"						"1"
						"labelText"						"Streamer Mode"
						"font"							"HudFontSmallBold"
						"textAlignment"					"west"
						"fgcolor"						"White"
					}
					"Separator_3"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Separator_3"
						"xpos"							"2"
						"ypos"							"0"
						"zpos"							"0"
						"wide"							"f6"
						"tall"							"1"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintBackground"				"1"
						"paintBackgroundtype"			"3"
						"bgcolor_override"				"TanDark"
						"pin_to_sibling"				"Streamer_Mode"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"Streamer_Mode_Explanation"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Streamer_Mode_Explanation"
						"xpos"							"-2"
						"ypos"							"5"
						"zpos"							"1"
						"wide"							"f10"
						"tall"							"0"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"wrap"							"1"
						"font"							"HudFontSmallest"
						"labeltext"						"Streamer mode aims to remove all the information that could be used to track the server you're playing in such as server names, player names, avatars and more in order to reduce the chance of stream snipes and DDoS."
						"textAlignment"					"North-West"
						"fgcolor"						"Gray"
						"auto_tall_tocontents"			"1"

						"pin_to_sibling"				"Separator_3"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"Streamer_Mode_ON"
					{
						"ControlName"					"CExButton"
						"fieldName"						"Streamer_Mode_ON"
						"xpos"							"0"
						"ypos"							"4"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"20"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"textAlignment"					"Center"
						"font"							"HudFontSmallBold"
						"command"						"engine m0_streamer_mode_ON; hud_reloadscheme; toggle mat_aaquality"
						"labelText"						"enabled"
						"sound_depressed"				"UI/buttonclick.wav"
						"use_proportional_insets"		"1"
						"proportionaltoparent"			"1"
						"actionsignallevel"				"5"
						"paintBackground"				"1"
						"auto_wide_tocontents"			"1"
						"textinsetx"					"20"

						"pin_to_sibling"				"Streamer_Mode_Explanation"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
					"Streamer_Mode_OFF"
					{
						"ControlName"					"CExButton"
						"fieldName"						"Streamer_Mode_OFF"
						"xpos"							"5"
						"ypos"							"0"
						"zpos"							"5"
						"wide"							"0"
						"tall"							"20"
						"visible"						"1"
						"enabled"						"1"
						"allcaps"						"1"
						"textAlignment"					"Center"
						"font"							"HudFontSmallBold"
						"command"						"engine m0_streamer_mode_OFF; hud_reloadscheme; toggle mat_aaquality"
						"labelText"						"Disabled"
						"sound_depressed"				"UI/buttonclick.wav"
						"use_proportional_insets"		"1"
						"proportionaltoparent"			"1"
						"actionsignallevel"				"5"
						"paintBackground"				"1"
						"auto_wide_tocontents"			"1"
						"textinsetx"					"20"

						"pin_to_sibling"				"Streamer_Mode_ON"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"
					}
					"Streamer_Mode_Warning"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Streamer_Mode_Warning"
						"xpos"							"0"
						"ypos"							"5"
						"zpos"							"1"
						"tall"							"0"
						"wide"							"f10"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"wrap"							"1"
						"font"							"HudFontSmallest"
						"labeltext"						"TF2 will freeze momentarily while enabling and disabling streamer mode, this is normal!"
						"textAlignment"					"north-west"
						"fgcolor"						"TeamRed"
						"auto_tall_tocontents"			"1"

						"pin_to_sibling"				"Streamer_Mode_ON"
						"pin_to_sibling_corner"			"PIN_BOTTOMLEFT"
					}
				}
			}
		}
	}
}