"Resource/UI/HudDemomanCharge.res"
{	
	"ChargeMeter"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"c162"
		"ypos"			"r21"
		"xpos_minmode"	"cs-0.5"
		"ypos_minmode"	"c30"
		"wide"			"53"
		"tall"			"6"
		"wide_minmode"	"40"
		"tall_minmode"	"4"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"fgcolor_override"		"255 255 255 255"	
	}					
}
