#base   "../../../../cfg/hudfixes/hud_float_damage.txt"
#base   "../../../../cfg/hudfixes/hud_last_damage.txt"
#base	"../../_centerhud/resource/ui/huddamageaccount.res"
#base	"../../_extras/resource/ui/huddamageaccount.res"
#base	"../../_tf2hud/resource/ui/huddamageaccount.res"