#base "../../_addons/_enabled/altmenu/altmenu.res"
#base "../../_addons/_enabled/centermenu/centermenu.res"
#base "../../_addons/_enabled/altcentermenu/altcentermenu.res"
#base "../../_centerhud/menu.res"
#base "../../resource/preload.res"
#base "#customizations/hud_customization.res"
